'use client';

import { useVisibilityAwareInterval } from '@/hooks/useVisibilityAwareInterval';
import { Activity, ArrowLeft, ArrowUpRight, CheckCircle2, Clock3, ExternalLink, Radio, ShieldAlert, Users, WalletCards, Zap } from 'lucide-react';
import Link from 'next/link';
import { useState } from 'react';
import s from './FintechCockpit.module.css';

export interface FintechCockpitService { id: string; trackingCode: string; fullName: string; serviceType: string; amount: string; currency: string; status: string; urgency: string; createdAt: string | Date; }
export interface FintechCockpitServiceStats { pending: number; todayCount: number; pendingUrgent: number; total: number; }
export interface FintechCockpitLiveService { id: string; name: string; desc: string; status: 'healthy' | 'degraded' | 'down' | 'idle'; latencyMs?: number; href?: string; iconName?: string; }
export interface FintechCockpitLiveEvent { id: string; type: 'deposit' | 'withdraw' | 'kyc' | 'order' | 'auth' | 'fraud'; actor: string; detail: string; amount?: { value: number; currency: string }; timestamp: string | number; href?: string; }
export interface FintechCockpitProps { userName: string; userRole: 'OWNER' | 'ADMIN' | 'AUTHOR' | 'SUPERADMIN'; kpi: { txn24h: number; activeCustomers: number; openFraudCases: number; pendingRequests: number; dealsVolume: number; dealsCurrency: string; }; services: { stats: FintechCockpitServiceStats; recent: FintechCockpitService[]; }; live: { services: FintechCockpitLiveService[]; events: FintechCockpitLiveEvent[]; activityBars: number[]; }; editorial?: React.ReactNode; }

const fa = new Intl.NumberFormat('fa-IR');
const labels: Record<string, string> = { INTERNATIONAL_TRANSFER: 'حواله بین‌المللی', ONLINE_PAYMENT: 'پرداخت آنلاین', TUITION_PAYMENT: 'پرداخت شهریه', FREELANCE_INCOME: 'نقد کردن درآمد', SOFTWARE_PURCHASE: 'خرید نرم‌افزار', CURRENCY_BUY: 'خرید ارز', CURRENCY_SELL: 'فروش ارز', OTHER: 'سایر خدمات' };
const status: Record<string, string> = { PENDING: 'در انتظار', IN_PROGRESS: 'در حال انجام', COMPLETED: 'تکمیل شده', CANCELLED: 'لغو شده' };
const ago = (value: string | Date, now = Date.now()) => { const minutes = Math.max(0, Math.floor((now - new Date(value).getTime()) / 60000)); return minutes < 1 ? 'همین حالا' : minutes < 60 ? `${fa.format(minutes)} دقیقه پیش` : `${fa.format(Math.floor(minutes / 60))} ساعت پیش`; };
const iconFor = (type: FintechCockpitLiveEvent['type']) => type === 'fraud' ? ShieldAlert : type === 'auth' ? CheckCircle2 : type === 'withdraw' ? ArrowUpRight : WalletCards;

function AtlasHeader({ userName, stats, events }: { userName: string; stats: FintechCockpitServiceStats; events: number }) {
  const [now, setNow] = useState(() => Date.now());
  useVisibilityAwareInterval(() => setNow(Date.now()), 30000);
  const hour = new Date(now).getHours();
  const greeting = hour < 12 ? 'صبح بخیر' : hour < 17 ? 'ظهر بخیر' : hour < 21 ? 'عصر بخیر' : 'شب بخیر';
  return <header className={s.atlasHeader}><div><span className={s.kicker}><span className={s.liveDot} />مرکز فرماندهی <time dir="ltr">{new Date(now).toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })}</time></span><h1>{greeting}، <em>{userName || 'مدیر'}</em></h1><p>{stats.pending > 0 ? `${fa.format(stats.pending)} درخواست در صف تصمیم‌گیری است.` : 'صف تصمیم‌گیری خالی است.'}</p></div><div className={s.headerReadout}><span>رویداد زنده</span><strong>{fa.format(events)}</strong><small>{new Date(now).toLocaleDateString('fa-IR', { weekday: 'long', day: 'numeric', month: 'long' })}</small></div></header>;
}

function SignalRail({ kpi, stats }: { kpi: FintechCockpitProps['kpi']; stats: FintechCockpitServiceStats }) {
  const signals = [{ label: 'صف تصمیم', value: stats.pending, href: '/dashboard/service-requests', tone: stats.pending ? 'warn' : 'ok', icon: Clock3 }, { label: 'فوری', value: stats.pendingUrgent, href: '/dashboard/service-requests', tone: stats.pendingUrgent ? 'danger' : 'ok', icon: Zap }, { label: 'ریسک باز', value: kpi.openFraudCases, href: '/dashboard/fraud-review', tone: kpi.openFraudCases ? 'danger' : 'ok', icon: ShieldAlert }, { label: 'تراکنش ۲۴ ساعت', value: kpi.txn24h, href: '/dashboard/audit-log', tone: 'neutral', icon: Activity }];
  return <aside className={s.signalRail} aria-label="سیگنال‌های قابل اقدام"><div className={s.railLabel}>NOW / PRIORITY</div>{signals.map(({ label, value, href, tone, icon: Icon }) => <Link key={label} href={href} className={`${s.signal} ${s[`tone_${tone}`]}`}><span className={s.signalIcon}><Icon size={15} /></span><span>{label}</span><strong>{fa.format(value)}</strong><ArrowLeft size={13} /></Link>)}</aside>;
}

function CommandLinks() { const links = [{ label: 'صرافی‌ها', hint: 'اعضا و نقش‌ها', href: '/dashboard/exchanges', icon: Users }, { label: 'نرخ‌های ارز', hint: 'بازار زنده', href: '/dashboard/exchange-rates', icon: WalletCards }, { label: 'گزارش‌ها', hint: 'تحلیل مالی', href: '/dashboard/reports', icon: Activity }, { label: 'پشتیبانی', hint: 'تیکت‌های باز', href: '/dashboard/helpdesk', icon: Radio }]; return <nav className={s.commands} aria-label="دسترسی سریع">{links.map(({ label, hint, href, icon: Icon }) => <Link key={href} href={href}><Icon size={16} /><span><b>{label}</b><small>{hint}</small></span><ArrowLeft size={13} /></Link>)}</nav>; }

function DecisionQueue({ recent, stats }: { recent: FintechCockpitService[]; stats: FintechCockpitServiceStats }) { return <section className={`${s.panel} ${s.queuePanel}`} aria-label="صف تصمیم‌گیری"><header className={s.panelHead}><div><span className={s.eyebrow}>DECISION QUEUE</span><h2>کارهایی که منتظر تو هستند</h2></div><Link href="/dashboard/service-requests" className={s.link}>باز کردن مرکز <ArrowLeft size={14} /></Link></header><div className={s.meta}><span><b>{fa.format(stats.pending)}</b> در انتظار</span><span><b>{fa.format(stats.todayCount)}</b> امروز</span><span className={stats.pendingUrgent ? s.alert : ''}><b>{fa.format(stats.pendingUrgent)}</b> فوری</span></div><ul className={s.queue}>{recent.length ? recent.map((item) => <li key={item.id}><Link href="/dashboard/service-requests"><span className={s.avatar}>{item.fullName.trim().slice(0, 1) || '؟'}</span><span className={s.identity}><strong>{item.fullName}</strong><small>{labels[item.serviceType] ?? item.serviceType} · <span dir="ltr">{item.trackingCode}</span></small></span><span className={s.amount}><b dir="ltr">{item.amount} {item.currency}</b><small className={item.urgency === 'URGENT' ? s.alert : ''}>{item.urgency === 'URGENT' ? 'فوری' : status[item.status] ?? item.status}</small><time>{ago(item.createdAt)}</time></span><ExternalLink size={14} className={s.open} /></Link></li>) : <li className={s.empty}><CheckCircle2 size={17} />صف درخواست‌ها خالی است</li>}</ul></section>; }

function ActivityDesk({ live }: { live: FintechCockpitProps['live'] }) { const [now, setNow] = useState(() => Date.now()); useVisibilityAwareInterval(() => setNow(Date.now()), 30000); const healthy = live.services.filter((service) => service.status === 'healthy').length; const score = live.services.length ? Math.round((healthy / live.services.length) * 100) : null; return <section className={`${s.panel} ${s.activityPanel}`} aria-label="نبض پلتفرم"><header className={s.panelHead}><div><span className={s.eyebrow}>SYSTEM PULSE</span><h2>آخرین حرکت سیستم</h2></div><span className={s.health}><span className={s.liveDot} />{score === null ? 'بدون داده' : `${fa.format(score)}٪ سالم`}</span></header><div className={s.services}>{live.services.slice(0, 4).map((service) => <div key={service.id}><span className={`${s.signalDot} ${s[`signal_${service.status}`]}`} /><span>{service.name}</span><small>{service.latencyMs == null ? 'بدون سنجه' : `${Math.round(service.latencyMs)}ms`}</small></div>)}</div>{live.activityBars.length > 0 && <div className={s.activity} aria-label="فعالیت ثبت‌شده">{live.activityBars.map((bar, i) => <i key={`${i}-${bar}`} style={{ blockSize: `${Math.max(4, Math.min(100, bar))}%` }} />)}</div>}<ol className={s.events}>{live.events.slice(0, 5).map((event) => { const Icon = iconFor(event.type); return <li key={event.id}><span className={s.eventMarker}><Icon size={14} /></span><span><strong>{event.actor}</strong><small>{event.detail}</small></span><time>{ago(new Date(event.timestamp), now)}</time></li>; })}</ol>{live.events.length === 0 && <div className={s.empty}><Clock3 size={17} />رویداد زنده‌ای ثبت نشده</div>}</section>; }

export function FintechCockpit({ userName, kpi, services, live, editorial }: FintechCockpitProps) { return <div className={s.root} dir="rtl"><AtlasHeader userName={userName} stats={services.stats} events={live.events.length} /><div className={s.atlasBody}><SignalRail kpi={kpi} stats={services.stats} /><main className={s.main}><CommandLinks /><div className={s.workspace}><DecisionQueue recent={services.recent} stats={services.stats} /><ActivityDesk live={live} /></div>{editorial ? <div className={s.editorial}>{editorial}</div> : null}</main></div></div>; }
export default FintechCockpit;
