// Code generated by ent, DO NOT EDIT.

package exchangerate

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the exchangerate type in the database.
	Label = "exchange_rate"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldRateType holds the string denoting the rate_type field in the database.
	FieldRateType = "rate_type"
	// FieldBuyRate holds the string denoting the buy_rate field in the database.
	FieldBuyRate = "buy_rate"
	// FieldSellRate holds the string denoting the sell_rate field in the database.
	FieldSellRate = "sell_rate"
	// FieldSingleRate holds the string denoting the single_rate field in the database.
	FieldSingleRate = "single_rate"
	// FieldBulkRate holds the string denoting the bulk_rate field in the database.
	FieldBulkRate = "bulk_rate"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldImageURL holds the string denoting the image_url field in the database.
	FieldImageURL = "image_url"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the exchangerate in the database.
	Table = "exchange_rates"
)

// Columns holds all SQL columns for exchangerate fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldCurrency,
	FieldRateType,
	FieldBuyRate,
	FieldSellRate,
	FieldSingleRate,
	FieldBulkRate,
	FieldDescription,
	FieldImageURL,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// RateType defines the type for the "rate_type" enum field.
type RateType string

// RateTypeBUY_SELL is the default value of the RateType enum.
const DefaultRateType = RateTypeBUY_SELL

// RateType values.
const (
	RateTypeBUY_SELL    RateType = "BUY_SELL"
	RateTypeSINGLE_BULK RateType = "SINGLE_BULK"
)

func (rt RateType) String() string {
	return string(rt)
}

// RateTypeValidator is a validator for the "rate_type" field enum values. It is called by the builders before save.
func RateTypeValidator(rt RateType) error {
	switch rt {
	case RateTypeBUY_SELL, RateTypeSINGLE_BULK:
		return nil
	default:
		return fmt.Errorf("exchangerate: invalid enum value for rate_type field: %q", rt)
	}
}

// OrderOption defines the ordering options for the ExchangeRate queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByRateType orders the results by the rate_type field.
func ByRateType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRateType, opts...).ToFunc()
}

// ByBuyRate orders the results by the buy_rate field.
func ByBuyRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyRate, opts...).ToFunc()
}

// BySellRate orders the results by the sell_rate field.
func BySellRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSellRate, opts...).ToFunc()
}

// BySingleRate orders the results by the single_rate field.
func BySingleRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSingleRate, opts...).ToFunc()
}

// ByBulkRate orders the results by the bulk_rate field.
func ByBulkRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBulkRate, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByImageURL orders the results by the image_url field.
func ByImageURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageURL, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
