// Code generated by ent, DO NOT EDIT.

package exchangerate

import (
	"biotak-go-backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldContainsFold(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldName, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldCurrency, v))
}

// BuyRate applies equality check predicate on the "buy_rate" field. It's identical to BuyRateEQ.
func BuyRate(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldBuyRate, v))
}

// SellRate applies equality check predicate on the "sell_rate" field. It's identical to SellRateEQ.
func SellRate(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldSellRate, v))
}

// SingleRate applies equality check predicate on the "single_rate" field. It's identical to SingleRateEQ.
func SingleRate(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldSingleRate, v))
}

// BulkRate applies equality check predicate on the "bulk_rate" field. It's identical to BulkRateEQ.
func BulkRate(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldBulkRate, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldDescription, v))
}

// ImageURL applies equality check predicate on the "image_url" field. It's identical to ImageURLEQ.
func ImageURL(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldImageURL, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldContainsFold(FieldName, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldContainsFold(FieldCurrency, v))
}

// RateTypeEQ applies the EQ predicate on the "rate_type" field.
func RateTypeEQ(v RateType) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldRateType, v))
}

// RateTypeNEQ applies the NEQ predicate on the "rate_type" field.
func RateTypeNEQ(v RateType) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNEQ(FieldRateType, v))
}

// RateTypeIn applies the In predicate on the "rate_type" field.
func RateTypeIn(vs ...RateType) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldIn(FieldRateType, vs...))
}

// RateTypeNotIn applies the NotIn predicate on the "rate_type" field.
func RateTypeNotIn(vs ...RateType) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNotIn(FieldRateType, vs...))
}

// BuyRateEQ applies the EQ predicate on the "buy_rate" field.
func BuyRateEQ(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldBuyRate, v))
}

// BuyRateNEQ applies the NEQ predicate on the "buy_rate" field.
func BuyRateNEQ(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNEQ(FieldBuyRate, v))
}

// BuyRateIn applies the In predicate on the "buy_rate" field.
func BuyRateIn(vs ...string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldIn(FieldBuyRate, vs...))
}

// BuyRateNotIn applies the NotIn predicate on the "buy_rate" field.
func BuyRateNotIn(vs ...string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNotIn(FieldBuyRate, vs...))
}

// BuyRateGT applies the GT predicate on the "buy_rate" field.
func BuyRateGT(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGT(FieldBuyRate, v))
}

// BuyRateGTE applies the GTE predicate on the "buy_rate" field.
func BuyRateGTE(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGTE(FieldBuyRate, v))
}

// BuyRateLT applies the LT predicate on the "buy_rate" field.
func BuyRateLT(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLT(FieldBuyRate, v))
}

// BuyRateLTE applies the LTE predicate on the "buy_rate" field.
func BuyRateLTE(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLTE(FieldBuyRate, v))
}

// BuyRateContains applies the Contains predicate on the "buy_rate" field.
func BuyRateContains(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldContains(FieldBuyRate, v))
}

// BuyRateHasPrefix applies the HasPrefix predicate on the "buy_rate" field.
func BuyRateHasPrefix(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldHasPrefix(FieldBuyRate, v))
}

// BuyRateHasSuffix applies the HasSuffix predicate on the "buy_rate" field.
func BuyRateHasSuffix(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldHasSuffix(FieldBuyRate, v))
}

// BuyRateIsNil applies the IsNil predicate on the "buy_rate" field.
func BuyRateIsNil() predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldIsNull(FieldBuyRate))
}

// BuyRateNotNil applies the NotNil predicate on the "buy_rate" field.
func BuyRateNotNil() predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNotNull(FieldBuyRate))
}

// BuyRateEqualFold applies the EqualFold predicate on the "buy_rate" field.
func BuyRateEqualFold(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEqualFold(FieldBuyRate, v))
}

// BuyRateContainsFold applies the ContainsFold predicate on the "buy_rate" field.
func BuyRateContainsFold(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldContainsFold(FieldBuyRate, v))
}

// SellRateEQ applies the EQ predicate on the "sell_rate" field.
func SellRateEQ(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldSellRate, v))
}

// SellRateNEQ applies the NEQ predicate on the "sell_rate" field.
func SellRateNEQ(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNEQ(FieldSellRate, v))
}

// SellRateIn applies the In predicate on the "sell_rate" field.
func SellRateIn(vs ...string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldIn(FieldSellRate, vs...))
}

// SellRateNotIn applies the NotIn predicate on the "sell_rate" field.
func SellRateNotIn(vs ...string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNotIn(FieldSellRate, vs...))
}

// SellRateGT applies the GT predicate on the "sell_rate" field.
func SellRateGT(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGT(FieldSellRate, v))
}

// SellRateGTE applies the GTE predicate on the "sell_rate" field.
func SellRateGTE(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGTE(FieldSellRate, v))
}

// SellRateLT applies the LT predicate on the "sell_rate" field.
func SellRateLT(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLT(FieldSellRate, v))
}

// SellRateLTE applies the LTE predicate on the "sell_rate" field.
func SellRateLTE(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLTE(FieldSellRate, v))
}

// SellRateContains applies the Contains predicate on the "sell_rate" field.
func SellRateContains(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldContains(FieldSellRate, v))
}

// SellRateHasPrefix applies the HasPrefix predicate on the "sell_rate" field.
func SellRateHasPrefix(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldHasPrefix(FieldSellRate, v))
}

// SellRateHasSuffix applies the HasSuffix predicate on the "sell_rate" field.
func SellRateHasSuffix(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldHasSuffix(FieldSellRate, v))
}

// SellRateIsNil applies the IsNil predicate on the "sell_rate" field.
func SellRateIsNil() predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldIsNull(FieldSellRate))
}

// SellRateNotNil applies the NotNil predicate on the "sell_rate" field.
func SellRateNotNil() predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNotNull(FieldSellRate))
}

// SellRateEqualFold applies the EqualFold predicate on the "sell_rate" field.
func SellRateEqualFold(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEqualFold(FieldSellRate, v))
}

// SellRateContainsFold applies the ContainsFold predicate on the "sell_rate" field.
func SellRateContainsFold(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldContainsFold(FieldSellRate, v))
}

// SingleRateEQ applies the EQ predicate on the "single_rate" field.
func SingleRateEQ(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldSingleRate, v))
}

// SingleRateNEQ applies the NEQ predicate on the "single_rate" field.
func SingleRateNEQ(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNEQ(FieldSingleRate, v))
}

// SingleRateIn applies the In predicate on the "single_rate" field.
func SingleRateIn(vs ...string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldIn(FieldSingleRate, vs...))
}

// SingleRateNotIn applies the NotIn predicate on the "single_rate" field.
func SingleRateNotIn(vs ...string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNotIn(FieldSingleRate, vs...))
}

// SingleRateGT applies the GT predicate on the "single_rate" field.
func SingleRateGT(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGT(FieldSingleRate, v))
}

// SingleRateGTE applies the GTE predicate on the "single_rate" field.
func SingleRateGTE(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGTE(FieldSingleRate, v))
}

// SingleRateLT applies the LT predicate on the "single_rate" field.
func SingleRateLT(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLT(FieldSingleRate, v))
}

// SingleRateLTE applies the LTE predicate on the "single_rate" field.
func SingleRateLTE(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLTE(FieldSingleRate, v))
}

// SingleRateContains applies the Contains predicate on the "single_rate" field.
func SingleRateContains(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldContains(FieldSingleRate, v))
}

// SingleRateHasPrefix applies the HasPrefix predicate on the "single_rate" field.
func SingleRateHasPrefix(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldHasPrefix(FieldSingleRate, v))
}

// SingleRateHasSuffix applies the HasSuffix predicate on the "single_rate" field.
func SingleRateHasSuffix(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldHasSuffix(FieldSingleRate, v))
}

// SingleRateIsNil applies the IsNil predicate on the "single_rate" field.
func SingleRateIsNil() predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldIsNull(FieldSingleRate))
}

// SingleRateNotNil applies the NotNil predicate on the "single_rate" field.
func SingleRateNotNil() predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNotNull(FieldSingleRate))
}

// SingleRateEqualFold applies the EqualFold predicate on the "single_rate" field.
func SingleRateEqualFold(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEqualFold(FieldSingleRate, v))
}

// SingleRateContainsFold applies the ContainsFold predicate on the "single_rate" field.
func SingleRateContainsFold(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldContainsFold(FieldSingleRate, v))
}

// BulkRateEQ applies the EQ predicate on the "bulk_rate" field.
func BulkRateEQ(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldBulkRate, v))
}

// BulkRateNEQ applies the NEQ predicate on the "bulk_rate" field.
func BulkRateNEQ(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNEQ(FieldBulkRate, v))
}

// BulkRateIn applies the In predicate on the "bulk_rate" field.
func BulkRateIn(vs ...string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldIn(FieldBulkRate, vs...))
}

// BulkRateNotIn applies the NotIn predicate on the "bulk_rate" field.
func BulkRateNotIn(vs ...string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNotIn(FieldBulkRate, vs...))
}

// BulkRateGT applies the GT predicate on the "bulk_rate" field.
func BulkRateGT(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGT(FieldBulkRate, v))
}

// BulkRateGTE applies the GTE predicate on the "bulk_rate" field.
func BulkRateGTE(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGTE(FieldBulkRate, v))
}

// BulkRateLT applies the LT predicate on the "bulk_rate" field.
func BulkRateLT(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLT(FieldBulkRate, v))
}

// BulkRateLTE applies the LTE predicate on the "bulk_rate" field.
func BulkRateLTE(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLTE(FieldBulkRate, v))
}

// BulkRateContains applies the Contains predicate on the "bulk_rate" field.
func BulkRateContains(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldContains(FieldBulkRate, v))
}

// BulkRateHasPrefix applies the HasPrefix predicate on the "bulk_rate" field.
func BulkRateHasPrefix(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldHasPrefix(FieldBulkRate, v))
}

// BulkRateHasSuffix applies the HasSuffix predicate on the "bulk_rate" field.
func BulkRateHasSuffix(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldHasSuffix(FieldBulkRate, v))
}

// BulkRateIsNil applies the IsNil predicate on the "bulk_rate" field.
func BulkRateIsNil() predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldIsNull(FieldBulkRate))
}

// BulkRateNotNil applies the NotNil predicate on the "bulk_rate" field.
func BulkRateNotNil() predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNotNull(FieldBulkRate))
}

// BulkRateEqualFold applies the EqualFold predicate on the "bulk_rate" field.
func BulkRateEqualFold(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEqualFold(FieldBulkRate, v))
}

// BulkRateContainsFold applies the ContainsFold predicate on the "bulk_rate" field.
func BulkRateContainsFold(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldContainsFold(FieldBulkRate, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldContainsFold(FieldDescription, v))
}

// ImageURLEQ applies the EQ predicate on the "image_url" field.
func ImageURLEQ(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldImageURL, v))
}

// ImageURLNEQ applies the NEQ predicate on the "image_url" field.
func ImageURLNEQ(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNEQ(FieldImageURL, v))
}

// ImageURLIn applies the In predicate on the "image_url" field.
func ImageURLIn(vs ...string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldIn(FieldImageURL, vs...))
}

// ImageURLNotIn applies the NotIn predicate on the "image_url" field.
func ImageURLNotIn(vs ...string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNotIn(FieldImageURL, vs...))
}

// ImageURLGT applies the GT predicate on the "image_url" field.
func ImageURLGT(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGT(FieldImageURL, v))
}

// ImageURLGTE applies the GTE predicate on the "image_url" field.
func ImageURLGTE(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGTE(FieldImageURL, v))
}

// ImageURLLT applies the LT predicate on the "image_url" field.
func ImageURLLT(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLT(FieldImageURL, v))
}

// ImageURLLTE applies the LTE predicate on the "image_url" field.
func ImageURLLTE(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLTE(FieldImageURL, v))
}

// ImageURLContains applies the Contains predicate on the "image_url" field.
func ImageURLContains(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldContains(FieldImageURL, v))
}

// ImageURLHasPrefix applies the HasPrefix predicate on the "image_url" field.
func ImageURLHasPrefix(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldHasPrefix(FieldImageURL, v))
}

// ImageURLHasSuffix applies the HasSuffix predicate on the "image_url" field.
func ImageURLHasSuffix(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldHasSuffix(FieldImageURL, v))
}

// ImageURLIsNil applies the IsNil predicate on the "image_url" field.
func ImageURLIsNil() predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldIsNull(FieldImageURL))
}

// ImageURLNotNil applies the NotNil predicate on the "image_url" field.
func ImageURLNotNil() predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNotNull(FieldImageURL))
}

// ImageURLEqualFold applies the EqualFold predicate on the "image_url" field.
func ImageURLEqualFold(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEqualFold(FieldImageURL, v))
}

// ImageURLContainsFold applies the ContainsFold predicate on the "image_url" field.
func ImageURLContainsFold(v string) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldContainsFold(FieldImageURL, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ExchangeRate) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ExchangeRate) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ExchangeRate) predicate.ExchangeRate {
	return predicate.ExchangeRate(sql.NotPredicates(p))
}
