package integration

import (
	"biotak-go-backend/internal/utils"
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"testing"
	"time"

	"github.com/golang-jwt/jwt/v5"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// Feature: go-backend-migration, Property 38: JWT Token Cross-Compatibility
// For any JWT token generated by the Go backend, it should be valid for authentication in the Next.js frontend, and vice versa.
// Validates: Requirements 11.2

// TestJWTCrossCompatibility tests that JWT tokens generated by Go can be validated by Next.js and vice versa
// This is critical for gradual migration where both systems need to accept tokens from each other

func TestJWTTokenStructureCompatibility(t *testing.T) {
	// Set up test environment with same secret as NextAuth
	os.Setenv("AUTH_SECRET", "test-secret-key-for-jwt-testing-minimum-32-chars")
	defer os.Unsetenv("AUTH_SECRET")

	t.Run("Go-generated token has NextAuth-compatible structure", func(t *testing.T) {
		userID := "user-123"
		email := "test@example.com"
		name := "Test User"
		role := "USER"
		emailVerified := time.Now()

		// Generate token using Go utilities
		token, err := utils.GenerateToken(userID, email, name, role, &emailVerified)
		require.NoError(t, err)
		require.NotEmpty(t, token)

		// Parse token to verify structure matches NextAuth expectations
		parsedToken, err := jwt.Parse(token, func(token *jwt.Token) (interface{}, error) {
			// Verify signing method is HS256 (same as NextAuth)
			if _, ok := token.Method.(*jwt.SigningMethodHMAC); !ok {
				return nil, fmt.Errorf("unexpected signing method: %v", token.Header["alg"])
			}
			return []byte(os.Getenv("AUTH_SECRET")), nil
		})
		require.NoError(t, err)
		require.True(t, parsedToken.Valid)

		// Verify claims structure
		claims, ok := parsedToken.Claims.(jwt.MapClaims)
		require.True(t, ok)

		// NextAuth uses "sub" for user ID
		assert.Equal(t, userID, claims["sub"])
		assert.Equal(t, email, claims["email"])
		assert.Equal(t, name, claims["name"])
		assert.Equal(t, role, claims["role"])
		assert.NotNil(t, claims["emailVerified"])

		// Verify standard JWT claims
		assert.NotNil(t, claims["exp"]) // Expiration
		assert.NotNil(t, claims["iat"]) // Issued at
		assert.NotNil(t, claims["nbf"]) // Not before
	})

	t.Run("Token expiration matches NextAuth (3 days)", func(t *testing.T) {
		userID := "user-456"
		email := "expiry@example.com"
		name := "Expiry Test"
		role := "USER"

		token, err := utils.GenerateToken(userID, email, name, role, nil)
		require.NoError(t, err)

		claims, err := utils.ValidateToken(token)
		require.NoError(t, err)

		// Verify expiration is 3 days from now (matching NextAuth session.maxAge)
		expectedExpiry := time.Now().Add(3 * 24 * time.Hour)
		actualExpiry := claims.ExpiresAt.Time

		// Allow 1 minute tolerance
		diff := actualExpiry.Sub(expectedExpiry).Abs()
		assert.Less(t, diff, time.Minute,
			"Token expiration should be 3 days (matching NextAuth configuration)")
	})

	t.Run("Token uses HS256 algorithm (same as NextAuth)", func(t *testing.T) {
		token, err := utils.GenerateToken("user-789", "algo@example.com", "Algo Test", "USER", nil)
		require.NoError(t, err)

		// Parse without validation to check algorithm
		parsedToken, _, err := jwt.NewParser().ParseUnverified(token, jwt.MapClaims{})
		require.NoError(t, err)

		// Verify algorithm is HS256
		assert.Equal(t, "HS256", parsedToken.Header["alg"],
			"Token should use HS256 algorithm (same as NextAuth)")
	})

	t.Run("Token with nil emailVerified is compatible", func(t *testing.T) {
		token, err := utils.GenerateToken("user-unverified", "unverified@example.com", "Unverified", "USER", nil)
		require.NoError(t, err)

		claims, err := utils.ValidateToken(token)
		require.NoError(t, err)

		// emailVerified should be nil/null (compatible with NextAuth)
		assert.Nil(t, claims.EmailVerified)
	})
}

func TestJWTClaimsRoundTrip(t *testing.T) {
	os.Setenv("AUTH_SECRET", "test-secret-key-for-jwt-testing-minimum-32-chars")
	defer os.Unsetenv("AUTH_SECRET")

	t.Run("All user information survives round trip", func(t *testing.T) {
		// Original user data
		originalUserID := "user-roundtrip-123"
		originalEmail := "roundtrip@example.com"
		originalName := "Round Trip User"
		originalRole := "AUTHOR"
		originalEmailVerified := time.Now().Truncate(time.Second) // Truncate to avoid precision issues

		// Generate token
		token, err := utils.GenerateToken(originalUserID, originalEmail, originalName, originalRole, &originalEmailVerified)
		require.NoError(t, err)

		// Validate and extract claims
		claims, err := utils.ValidateToken(token)
		require.NoError(t, err)

		// Verify all fields match exactly
		assert.Equal(t, originalUserID, claims.UserID, "UserID should match")
		assert.Equal(t, originalEmail, claims.Email, "Email should match")
		assert.Equal(t, originalName, claims.Name, "Name should match")
		assert.Equal(t, originalRole, claims.Role, "Role should match")
		
		// Verify emailVerified timestamp
		require.NotNil(t, claims.EmailVerified)
		actualEmailVerified := time.Unix(*claims.EmailVerified, 0)
		assert.Equal(t, originalEmailVerified.Unix(), actualEmailVerified.Unix(),
			"EmailVerified timestamp should match")
	})

	t.Run("Token can be refreshed maintaining user data", func(t *testing.T) {
		originalUserID := "user-refresh-456"
		originalEmail := "refresh@example.com"
		originalName := "Refresh User"
		originalRole := "ADMIN"
		originalEmailVerified := time.Now()

		// Generate original token
		originalToken, err := utils.GenerateToken(originalUserID, originalEmail, originalName, originalRole, &originalEmailVerified)
		require.NoError(t, err)

		// Wait a moment to ensure timestamps differ
		time.Sleep(time.Second)

		// Refresh token
		newToken, err := utils.RefreshToken(originalToken)
		require.NoError(t, err)
		assert.NotEqual(t, originalToken, newToken, "Refreshed token should be different")

		// Validate new token
		newClaims, err := utils.ValidateToken(newToken)
		require.NoError(t, err)

		// Verify user data is preserved
		assert.Equal(t, originalUserID, newClaims.UserID)
		assert.Equal(t, originalEmail, newClaims.Email)
		assert.Equal(t, originalName, newClaims.Name)
		assert.Equal(t, originalRole, newClaims.Role)

		// Verify new token has fresh expiration
		assert.True(t, newClaims.ExpiresAt.Time.After(time.Now()))
	})
}

func TestJWTSecretCompatibility(t *testing.T) {
	t.Run("Same secret produces verifiable tokens", func(t *testing.T) {
		secret := "shared-secret-between-go-and-nextjs-minimum-32-chars"
		os.Setenv("AUTH_SECRET", secret)
		defer os.Unsetenv("AUTH_SECRET")

		// Generate token with Go
		token, err := utils.GenerateToken("user-123", "test@example.com", "Test", "USER", nil)
		require.NoError(t, err)

		// Verify token can be validated with same secret
		claims, err := utils.ValidateToken(token)
		require.NoError(t, err)
		assert.Equal(t, "user-123", claims.UserID)
	})

	t.Run("Different secret fails validation", func(t *testing.T) {
		// Generate token with one secret
		os.Setenv("AUTH_SECRET", "secret-one-minimum-32-characters-long")
		token, err := utils.GenerateToken("user-456", "test@example.com", "Test", "USER", nil)
		require.NoError(t, err)

		// Try to validate with different secret
		os.Setenv("AUTH_SECRET", "secret-two-minimum-32-characters-long")
		_, err = utils.ValidateToken(token)
		assert.Error(t, err, "Token should fail validation with different secret")
	})
}

// Integration tests that require both Go and Next.js servers running
// These tests are skipped in short mode and require manual setup

func TestGoGeneratedTokenWithNextJS(t *testing.T) {
	if testing.Short() {
		t.Skip("Skipping integration test in short mode - requires both servers running")
	}

	// Generate a token using Go backend
	registerBody := map[string]interface{}{
		"email":    fmt.Sprintf("jwt-test-%d@example.com", time.Now().Unix()),
		"password": "testpassword123",
		"name":     "JWT Test User",
	}

	resp, body := makeJWTRequest(t, goAPIBaseURL+"/auth/register", "POST", registerBody, "")
	require.Equal(t, http.StatusCreated, resp.StatusCode)

	var result map[string]interface{}
	err := json.Unmarshal(body, &result)
	require.NoError(t, err)

	goToken, ok := result["accessToken"].(string)
	require.True(t, ok, "accessToken should be a string")
	require.NotEmpty(t, goToken)

	// Try to use the Go-generated token with Next.js API
	nextJSResp, _ := makeJWTRequest(t, nextJSAPIBaseURL+"/auth/me", "GET", nil, goToken)

	// Next.js should accept the Go-generated token
	assert.Equal(t, http.StatusOK, nextJSResp.StatusCode,
		"Next.js should accept Go-generated JWT token")
}

func TestNextJSGeneratedTokenWithGo(t *testing.T) {
	if testing.Short() {
		t.Skip("Skipping integration test in short mode - requires both servers running")
	}

	// Generate a token using Next.js backend
	registerBody := map[string]interface{}{
		"email":    fmt.Sprintf("jwt-test-%d@example.com", time.Now().Unix()),
		"password": "testpassword123",
		"name":     "JWT Test User",
	}

	resp, body := makeJWTRequest(t, nextJSAPIBaseURL+"/auth/register", "POST", registerBody, "")
	require.Equal(t, http.StatusCreated, resp.StatusCode)

	var result map[string]interface{}
	err := json.Unmarshal(body, &result)
	require.NoError(t, err)

	nextJSToken, ok := result["accessToken"].(string)
	require.True(t, ok, "accessToken should be a string")
	require.NotEmpty(t, nextJSToken)

	// Try to use the Next.js-generated token with Go API
	goResp, _ := makeJWTRequest(t, goAPIBaseURL+"/auth/me", "GET", nil, nextJSToken)

	// Go should accept the Next.js-generated token
	assert.Equal(t, http.StatusOK, goResp.StatusCode,
		"Go should accept Next.js-generated JWT token")
}

func TestJWTRefreshTokenCompatibility(t *testing.T) {
	if testing.Short() {
		t.Skip("Skipping integration test in short mode - requires both servers running")
	}

	// Generate a token using Go
	registerBody := map[string]interface{}{
		"email":    fmt.Sprintf("jwt-test-%d@example.com", time.Now().Unix()),
		"password": "testpassword123",
		"name":     "JWT Test User",
	}

	resp, body := makeJWTRequest(t, goAPIBaseURL+"/auth/register", "POST", registerBody, "")
	require.Equal(t, http.StatusCreated, resp.StatusCode)

	var result map[string]interface{}
	err := json.Unmarshal(body, &result)
	require.NoError(t, err)

	originalToken, ok := result["accessToken"].(string)
	require.True(t, ok)

	// Refresh the token using Go API
	refreshResp, refreshBody := makeJWTRequest(t, goAPIBaseURL+"/auth/refresh", "POST", nil, originalToken)
	assert.Equal(t, http.StatusOK, refreshResp.StatusCode)

	// Parse refresh response
	var refreshResult map[string]interface{}
	err = json.Unmarshal(refreshBody, &refreshResult)
	require.NoError(t, err)

	newToken, ok := refreshResult["accessToken"].(string)
	require.True(t, ok)
	require.NotEmpty(t, newToken)
	assert.NotEqual(t, originalToken, newToken, "Refreshed token should be different")

	// Verify the new token works with both systems
	goResp, _ := makeJWTRequest(t, goAPIBaseURL+"/auth/me", "GET", nil, newToken)
	assert.Equal(t, http.StatusOK, goResp.StatusCode)

	nextJSResp, _ := makeJWTRequest(t, nextJSAPIBaseURL+"/auth/me", "GET", nil, newToken)
	assert.Equal(t, http.StatusOK, nextJSResp.StatusCode)
}

// Helper functions

func makeJWTRequest(t *testing.T, url, method string, body map[string]interface{}, token string) (*http.Response, []byte) {
	var reqBody io.Reader
	if body != nil {
		jsonBody, err := json.Marshal(body)
		require.NoError(t, err)
		reqBody = bytes.NewBuffer(jsonBody)
	}

	req, err := http.NewRequest(method, url, reqBody)
	require.NoError(t, err)

	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}

	if token != "" {
		req.Header.Set("Authorization", "Bearer "+token)
	}

	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Do(req)
	require.NoError(t, err)
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	require.NoError(t, err)

	return resp, respBody
}
