package integration

import (
	"biotak-go-backend/internal/utils"
	"encoding/json"
	"fmt"
	"net/http"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestJWTCrossCompatibility tests that JWT tokens generated by Go can be validated by Next.js and vice versa
// This is critical for gradual migration where both systems need to accept tokens from each other

func TestGoGeneratedTokenWithNextJS(t *testing.T) {
	if testing.Short() {
		t.Skip("Skipping integration test in short mode")
	}

	// Generate a token using Go backend
	registerBody := map[string]interface{}{
		"email":    fmt.Sprintf("jwt-test-%d@example.com", time.Now().Unix()),
		"password": "testpassword123",
		"name":     "JWT Test User",
	}

	resp, body := makeRequest(t, goAPIBaseURL+"/auth/register", "POST", registerBody)
	require.Equal(t, http.StatusCreated, resp.StatusCode)

	var result map[string]interface{}
	err := json.Unmarshal(body, &result)
	require.NoError(t, err)

	goToken, ok := result["accessToken"].(string)
	require.True(t, ok, "accessToken should be a string")
	require.NotEmpty(t, goToken)

	// Try to use the Go-generated token with Next.js API
	req, err := http.NewRequest("GET", nextJSAPIBaseURL+"/auth/me", nil)
	require.NoError(t, err)
	req.Header.Set("Authorization", "Bearer "+goToken)

	client := &http.Client{Timeout: 10 * time.Second}
	nextJSResp, err := client.Do(req)
	require.NoError(t, err)
	defer nextJSResp.Body.Close()

	// Next.js should accept the Go-generated token
	assert.Equal(t, http.StatusOK, nextJSResp.StatusCode,
		"Next.js should accept Go-generated JWT token")
}

func TestNextJSGeneratedTokenWithGo(t *testing.T) {
	if testing.Short() {
		t.Skip("Skipping integration test in short mode")
	}

	// Generate a token using Next.js backend
	registerBody := map[string]interface{}{
		"email":    fmt.Sprintf("jwt-test-%d@example.com", time.Now().Unix()),
		"password": "testpassword123",
		"name":     "JWT Test User",
	}

	resp, body := makeRequest(t, nextJSAPIBaseURL+"/auth/register", "POST", registerBody)
	require.Equal(t, http.StatusCreated, resp.StatusCode)

	var result map[string]interface{}
	err := json.Unmarshal(body, &result)
	require.NoError(t, err)

	nextJSToken, ok := result["accessToken"].(string)
	require.True(t, ok, "accessToken should be a string")
	require.NotEmpty(t, nextJSToken)

	// Try to use the Next.js-generated token with Go API
	req, err := http.NewRequest("GET", goAPIBaseURL+"/auth/me", nil)
	require.NoError(t, err)
	req.Header.Set("Authorization", "Bearer "+nextJSToken)

	client := &http.Client{Timeout: 10 * time.Second}
	goResp, err := client.Do(req)
	require.NoError(t, err)
	defer goResp.Body.Close()

	// Go should accept the Next.js-generated token
	assert.Equal(t, http.StatusOK, goResp.StatusCode,
		"Go should accept Next.js-generated JWT token")
}

func TestJWTTokenStructure(t *testing.T) {
	if testing.Short() {
		t.Skip("Skipping integration test in short mode")
	}

	// Generate tokens from both systems
	registerBody := map[string]interface{}{
		"email":    fmt.Sprintf("jwt-test-%d@example.com", time.Now().Unix()),
		"password": "testpassword123",
		"name":     "JWT Test User",
	}

	// Get Go token
	goResp, goBody := makeRequest(t, goAPIBaseURL+"/auth/register", "POST", registerBody)
	require.Equal(t, http.StatusCreated, goResp.StatusCode)

	var goResult map[string]interface{}
	err := json.Unmarshal(goBody, &goResult)
	require.NoError(t, err)

	goToken, ok := goResult["accessToken"].(string)
	require.True(t, ok)

	// Get Next.js token (use different email)
	registerBody["email"] = fmt.Sprintf("jwt-test-%d@example.com", time.Now().Unix()+1)
	nextJSResp, nextJSBody := makeRequest(t, nextJSAPIBaseURL+"/auth/register", "POST", registerBody)
	require.Equal(t, http.StatusCreated, nextJSResp.StatusCode)

	var nextJSResult map[string]interface{}
	err = json.Unmarshal(nextJSBody, &nextJSResult)
	require.NoError(t, err)

	nextJSToken, ok := nextJSResult["accessToken"].(string)
	require.True(t, ok)

	// Validate both tokens using Go's JWT utilities
	goClaims, err := utils.ValidateToken(goToken)
	require.NoError(t, err, "Go token should be valid")

	nextJSClaims, err := utils.ValidateToken(nextJSToken)
	require.NoError(t, err, "Next.js token should be valid")

	// Both should have the same structure
	assert.NotEmpty(t, goClaims.UserID)
	assert.NotEmpty(t, goClaims.Email)
	assert.NotEmpty(t, goClaims.Role)

	assert.NotEmpty(t, nextJSClaims.UserID)
	assert.NotEmpty(t, nextJSClaims.Email)
	assert.NotEmpty(t, nextJSClaims.Role)
}

func TestJWTTokenExpiration(t *testing.T) {
	if testing.Short() {
		t.Skip("Skipping integration test in short mode")
	}

	// Generate a token
	registerBody := map[string]interface{}{
		"email":    fmt.Sprintf("jwt-test-%d@example.com", time.Now().Unix()),
		"password": "testpassword123",
		"name":     "JWT Test User",
	}

	resp, body := makeRequest(t, goAPIBaseURL+"/auth/register", "POST", registerBody)
	require.Equal(t, http.StatusCreated, resp.StatusCode)

	var result map[string]interface{}
	err := json.Unmarshal(body, &result)
	require.NoError(t, err)

	token, ok := result["accessToken"].(string)
	require.True(t, ok)

	expiresIn, ok := result["expiresIn"].(float64)
	require.True(t, ok)

	// Verify expiration time is 3 days (259200 seconds)
	assert.Equal(t, float64(259200), expiresIn,
		"Token should expire in 3 days (259200 seconds)")

	// Validate token claims
	claims, err := utils.ValidateToken(token)
	require.NoError(t, err)

	// Check that expiration is approximately 3 days from now
	expectedExpiry := time.Now().Add(3 * 24 * time.Hour)
	actualExpiry := time.Unix(claims.ExpiresAt, 0)

	// Allow 1 minute tolerance
	diff := actualExpiry.Sub(expectedExpiry).Abs()
	assert.Less(t, diff, time.Minute,
		"Token expiration should be approximately 3 days from now")
}

func TestJWTRefreshTokenCompatibility(t *testing.T) {
	if testing.Short() {
		t.Skip("Skipping integration test in short mode")
	}

	// Generate a token using Go
	registerBody := map[string]interface{}{
		"email":    fmt.Sprintf("jwt-test-%d@example.com", time.Now().Unix()),
		"password": "testpassword123",
		"name":     "JWT Test User",
	}

	resp, body := makeRequest(t, goAPIBaseURL+"/auth/register", "POST", registerBody)
	require.Equal(t, http.StatusCreated, resp.StatusCode)

	var result map[string]interface{}
	err := json.Unmarshal(body, &result)
	require.NoError(t, err)

	originalToken, ok := result["accessToken"].(string)
	require.True(t, ok)

	// Refresh the token using Go API
	req, err := http.NewRequest("POST", goAPIBaseURL+"/auth/refresh", nil)
	require.NoError(t, err)
	req.Header.Set("Authorization", "Bearer "+originalToken)

	client := &http.Client{Timeout: 10 * time.Second}
	refreshResp, err := client.Do(req)
	require.NoError(t, err)
	defer refreshResp.Body.Close()

	assert.Equal(t, http.StatusOK, refreshResp.StatusCode)

	// Parse refresh response
	var refreshResult map[string]interface{}
	refreshBody, err := io.ReadAll(refreshResp.Body)
	require.NoError(t, err)
	err = json.Unmarshal(refreshBody, &refreshResult)
	require.NoError(t, err)

	newToken, ok := refreshResult["accessToken"].(string)
	require.True(t, ok)
	require.NotEmpty(t, newToken)
	assert.NotEqual(t, originalToken, newToken, "Refreshed token should be different")

	// Verify the new token works with both systems
	// Test with Go API
	req, err = http.NewRequest("GET", goAPIBaseURL+"/auth/me", nil)
	require.NoError(t, err)
	req.Header.Set("Authorization", "Bearer "+newToken)

	goResp, err := client.Do(req)
	require.NoError(t, err)
	defer goResp.Body.Close()
	assert.Equal(t, http.StatusOK, goResp.StatusCode)

	// Test with Next.js API
	req, err = http.NewRequest("GET", nextJSAPIBaseURL+"/auth/me", nil)
	require.NoError(t, err)
	req.Header.Set("Authorization", "Bearer "+newToken)

	nextJSResp, err := client.Do(req)
	require.NoError(t, err)
	defer nextJSResp.Body.Close()
	assert.Equal(t, http.StatusOK, nextJSResp.StatusCode)
}

func TestJWTBlacklistCompatibility(t *testing.T) {
	if testing.Short() {
		t.Skip("Skipping integration test in short mode")
	}

	// Generate a token
	registerBody := map[string]interface{}{
		"email":    fmt.Sprintf("jwt-test-%d@example.com", time.Now().Unix()),
		"password": "testpassword123",
		"name":     "JWT Test User",
	}

	resp, body := makeRequest(t, goAPIBaseURL+"/auth/register", "POST", registerBody)
	require.Equal(t, http.StatusCreated, resp.StatusCode)

	var result map[string]interface{}
	err := json.Unmarshal(body, &result)
	require.NoError(t, err)

	token, ok := result["accessToken"].(string)
	require.True(t, ok)

	// Logout using Go API (blacklists the token)
	req, err := http.NewRequest("POST", goAPIBaseURL+"/auth/logout", nil)
	require.NoError(t, err)
	req.Header.Set("Authorization", "Bearer "+token)

	client := &http.Client{Timeout: 10 * time.Second}
	logoutResp, err := client.Do(req)
	require.NoError(t, err)
	defer logoutResp.Body.Close()
	assert.Equal(t, http.StatusOK, logoutResp.StatusCode)

	// Try to use the blacklisted token with Go API
	req, err = http.NewRequest("GET", goAPIBaseURL+"/auth/me", nil)
	require.NoError(t, err)
	req.Header.Set("Authorization", "Bearer "+token)

	goResp, err := client.Do(req)
	require.NoError(t, err)
	defer goResp.Body.Close()
	assert.Equal(t, http.StatusUnauthorized, goResp.StatusCode,
		"Go API should reject blacklisted token")

	// Try to use the blacklisted token with Next.js API
	req, err = http.NewRequest("GET", nextJSAPIBaseURL+"/auth/me", nil)
	require.NoError(t, err)
	req.Header.Set("Authorization", "Bearer "+token)

	nextJSResp, err := client.Do(req)
	require.NoError(t, err)
	defer nextJSResp.Body.Close()
	assert.Equal(t, http.StatusUnauthorized, nextJSResp.StatusCode,
		"Next.js API should reject blacklisted token")
}
