// Code generated by ent, DO NOT EDIT.

package dailyanalytics

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the dailyanalytics type in the database.
	Label = "daily_analytics"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDate holds the string denoting the date field in the database.
	FieldDate = "date"
	// FieldTotalViews holds the string denoting the total_views field in the database.
	FieldTotalViews = "total_views"
	// FieldTotalComments holds the string denoting the total_comments field in the database.
	FieldTotalComments = "total_comments"
	// FieldNewUsers holds the string denoting the new_users field in the database.
	FieldNewUsers = "new_users"
	// FieldNewPosts holds the string denoting the new_posts field in the database.
	FieldNewPosts = "new_posts"
	// FieldPublishedPosts holds the string denoting the published_posts field in the database.
	FieldPublishedPosts = "published_posts"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the dailyanalytics in the database.
	Table = "daily_analytics"
)

// Columns holds all SQL columns for dailyanalytics fields.
var Columns = []string{
	FieldID,
	FieldDate,
	FieldTotalViews,
	FieldTotalComments,
	FieldNewUsers,
	FieldNewPosts,
	FieldPublishedPosts,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTotalViews holds the default value on creation for the "total_views" field.
	DefaultTotalViews int
	// TotalViewsValidator is a validator for the "total_views" field. It is called by the builders before save.
	TotalViewsValidator func(int) error
	// DefaultTotalComments holds the default value on creation for the "total_comments" field.
	DefaultTotalComments int
	// TotalCommentsValidator is a validator for the "total_comments" field. It is called by the builders before save.
	TotalCommentsValidator func(int) error
	// DefaultNewUsers holds the default value on creation for the "new_users" field.
	DefaultNewUsers int
	// NewUsersValidator is a validator for the "new_users" field. It is called by the builders before save.
	NewUsersValidator func(int) error
	// DefaultNewPosts holds the default value on creation for the "new_posts" field.
	DefaultNewPosts int
	// NewPostsValidator is a validator for the "new_posts" field. It is called by the builders before save.
	NewPostsValidator func(int) error
	// DefaultPublishedPosts holds the default value on creation for the "published_posts" field.
	DefaultPublishedPosts int
	// PublishedPostsValidator is a validator for the "published_posts" field. It is called by the builders before save.
	PublishedPostsValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the DailyAnalytics queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDate orders the results by the date field.
func ByDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDate, opts...).ToFunc()
}

// ByTotalViews orders the results by the total_views field.
func ByTotalViews(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalViews, opts...).ToFunc()
}

// ByTotalComments orders the results by the total_comments field.
func ByTotalComments(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalComments, opts...).ToFunc()
}

// ByNewUsers orders the results by the new_users field.
func ByNewUsers(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNewUsers, opts...).ToFunc()
}

// ByNewPosts orders the results by the new_posts field.
func ByNewPosts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNewPosts, opts...).ToFunc()
}

// ByPublishedPosts orders the results by the published_posts field.
func ByPublishedPosts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedPosts, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
