// Code generated by ent, DO NOT EDIT.

package dailyanalytics

import (
	"biotak-go-backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldContainsFold(FieldID, id))
}

// Date applies equality check predicate on the "date" field. It's identical to DateEQ.
func Date(v time.Time) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldEQ(FieldDate, v))
}

// TotalViews applies equality check predicate on the "total_views" field. It's identical to TotalViewsEQ.
func TotalViews(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldEQ(FieldTotalViews, v))
}

// TotalComments applies equality check predicate on the "total_comments" field. It's identical to TotalCommentsEQ.
func TotalComments(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldEQ(FieldTotalComments, v))
}

// NewUsers applies equality check predicate on the "new_users" field. It's identical to NewUsersEQ.
func NewUsers(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldEQ(FieldNewUsers, v))
}

// NewPosts applies equality check predicate on the "new_posts" field. It's identical to NewPostsEQ.
func NewPosts(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldEQ(FieldNewPosts, v))
}

// PublishedPosts applies equality check predicate on the "published_posts" field. It's identical to PublishedPostsEQ.
func PublishedPosts(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldEQ(FieldPublishedPosts, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldEQ(FieldCreatedAt, v))
}

// DateEQ applies the EQ predicate on the "date" field.
func DateEQ(v time.Time) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldEQ(FieldDate, v))
}

// DateNEQ applies the NEQ predicate on the "date" field.
func DateNEQ(v time.Time) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldNEQ(FieldDate, v))
}

// DateIn applies the In predicate on the "date" field.
func DateIn(vs ...time.Time) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldIn(FieldDate, vs...))
}

// DateNotIn applies the NotIn predicate on the "date" field.
func DateNotIn(vs ...time.Time) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldNotIn(FieldDate, vs...))
}

// DateGT applies the GT predicate on the "date" field.
func DateGT(v time.Time) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldGT(FieldDate, v))
}

// DateGTE applies the GTE predicate on the "date" field.
func DateGTE(v time.Time) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldGTE(FieldDate, v))
}

// DateLT applies the LT predicate on the "date" field.
func DateLT(v time.Time) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldLT(FieldDate, v))
}

// DateLTE applies the LTE predicate on the "date" field.
func DateLTE(v time.Time) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldLTE(FieldDate, v))
}

// TotalViewsEQ applies the EQ predicate on the "total_views" field.
func TotalViewsEQ(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldEQ(FieldTotalViews, v))
}

// TotalViewsNEQ applies the NEQ predicate on the "total_views" field.
func TotalViewsNEQ(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldNEQ(FieldTotalViews, v))
}

// TotalViewsIn applies the In predicate on the "total_views" field.
func TotalViewsIn(vs ...int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldIn(FieldTotalViews, vs...))
}

// TotalViewsNotIn applies the NotIn predicate on the "total_views" field.
func TotalViewsNotIn(vs ...int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldNotIn(FieldTotalViews, vs...))
}

// TotalViewsGT applies the GT predicate on the "total_views" field.
func TotalViewsGT(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldGT(FieldTotalViews, v))
}

// TotalViewsGTE applies the GTE predicate on the "total_views" field.
func TotalViewsGTE(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldGTE(FieldTotalViews, v))
}

// TotalViewsLT applies the LT predicate on the "total_views" field.
func TotalViewsLT(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldLT(FieldTotalViews, v))
}

// TotalViewsLTE applies the LTE predicate on the "total_views" field.
func TotalViewsLTE(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldLTE(FieldTotalViews, v))
}

// TotalCommentsEQ applies the EQ predicate on the "total_comments" field.
func TotalCommentsEQ(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldEQ(FieldTotalComments, v))
}

// TotalCommentsNEQ applies the NEQ predicate on the "total_comments" field.
func TotalCommentsNEQ(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldNEQ(FieldTotalComments, v))
}

// TotalCommentsIn applies the In predicate on the "total_comments" field.
func TotalCommentsIn(vs ...int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldIn(FieldTotalComments, vs...))
}

// TotalCommentsNotIn applies the NotIn predicate on the "total_comments" field.
func TotalCommentsNotIn(vs ...int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldNotIn(FieldTotalComments, vs...))
}

// TotalCommentsGT applies the GT predicate on the "total_comments" field.
func TotalCommentsGT(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldGT(FieldTotalComments, v))
}

// TotalCommentsGTE applies the GTE predicate on the "total_comments" field.
func TotalCommentsGTE(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldGTE(FieldTotalComments, v))
}

// TotalCommentsLT applies the LT predicate on the "total_comments" field.
func TotalCommentsLT(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldLT(FieldTotalComments, v))
}

// TotalCommentsLTE applies the LTE predicate on the "total_comments" field.
func TotalCommentsLTE(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldLTE(FieldTotalComments, v))
}

// NewUsersEQ applies the EQ predicate on the "new_users" field.
func NewUsersEQ(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldEQ(FieldNewUsers, v))
}

// NewUsersNEQ applies the NEQ predicate on the "new_users" field.
func NewUsersNEQ(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldNEQ(FieldNewUsers, v))
}

// NewUsersIn applies the In predicate on the "new_users" field.
func NewUsersIn(vs ...int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldIn(FieldNewUsers, vs...))
}

// NewUsersNotIn applies the NotIn predicate on the "new_users" field.
func NewUsersNotIn(vs ...int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldNotIn(FieldNewUsers, vs...))
}

// NewUsersGT applies the GT predicate on the "new_users" field.
func NewUsersGT(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldGT(FieldNewUsers, v))
}

// NewUsersGTE applies the GTE predicate on the "new_users" field.
func NewUsersGTE(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldGTE(FieldNewUsers, v))
}

// NewUsersLT applies the LT predicate on the "new_users" field.
func NewUsersLT(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldLT(FieldNewUsers, v))
}

// NewUsersLTE applies the LTE predicate on the "new_users" field.
func NewUsersLTE(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldLTE(FieldNewUsers, v))
}

// NewPostsEQ applies the EQ predicate on the "new_posts" field.
func NewPostsEQ(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldEQ(FieldNewPosts, v))
}

// NewPostsNEQ applies the NEQ predicate on the "new_posts" field.
func NewPostsNEQ(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldNEQ(FieldNewPosts, v))
}

// NewPostsIn applies the In predicate on the "new_posts" field.
func NewPostsIn(vs ...int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldIn(FieldNewPosts, vs...))
}

// NewPostsNotIn applies the NotIn predicate on the "new_posts" field.
func NewPostsNotIn(vs ...int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldNotIn(FieldNewPosts, vs...))
}

// NewPostsGT applies the GT predicate on the "new_posts" field.
func NewPostsGT(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldGT(FieldNewPosts, v))
}

// NewPostsGTE applies the GTE predicate on the "new_posts" field.
func NewPostsGTE(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldGTE(FieldNewPosts, v))
}

// NewPostsLT applies the LT predicate on the "new_posts" field.
func NewPostsLT(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldLT(FieldNewPosts, v))
}

// NewPostsLTE applies the LTE predicate on the "new_posts" field.
func NewPostsLTE(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldLTE(FieldNewPosts, v))
}

// PublishedPostsEQ applies the EQ predicate on the "published_posts" field.
func PublishedPostsEQ(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldEQ(FieldPublishedPosts, v))
}

// PublishedPostsNEQ applies the NEQ predicate on the "published_posts" field.
func PublishedPostsNEQ(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldNEQ(FieldPublishedPosts, v))
}

// PublishedPostsIn applies the In predicate on the "published_posts" field.
func PublishedPostsIn(vs ...int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldIn(FieldPublishedPosts, vs...))
}

// PublishedPostsNotIn applies the NotIn predicate on the "published_posts" field.
func PublishedPostsNotIn(vs ...int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldNotIn(FieldPublishedPosts, vs...))
}

// PublishedPostsGT applies the GT predicate on the "published_posts" field.
func PublishedPostsGT(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldGT(FieldPublishedPosts, v))
}

// PublishedPostsGTE applies the GTE predicate on the "published_posts" field.
func PublishedPostsGTE(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldGTE(FieldPublishedPosts, v))
}

// PublishedPostsLT applies the LT predicate on the "published_posts" field.
func PublishedPostsLT(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldLT(FieldPublishedPosts, v))
}

// PublishedPostsLTE applies the LTE predicate on the "published_posts" field.
func PublishedPostsLTE(v int) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldLTE(FieldPublishedPosts, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DailyAnalytics) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DailyAnalytics) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DailyAnalytics) predicate.DailyAnalytics {
	return predicate.DailyAnalytics(sql.NotPredicates(p))
}
