// Code generated by ent, DO NOT EDIT.

package ent

import (
	"biotak-go-backend/ent/dailyanalytics"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// DailyAnalytics is the model entity for the DailyAnalytics schema.
type DailyAnalytics struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Date for this analytics record
	Date time.Time `json:"date,omitempty"`
	// Total post views for the day
	TotalViews int `json:"total_views,omitempty"`
	// Total comments created for the day
	TotalComments int `json:"total_comments,omitempty"`
	// New users registered for the day
	NewUsers int `json:"new_users,omitempty"`
	// New posts created for the day
	NewPosts int `json:"new_posts,omitempty"`
	// Posts published for the day
	PublishedPosts int `json:"published_posts,omitempty"`
	// Timestamp when record was created
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DailyAnalytics) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dailyanalytics.FieldTotalViews, dailyanalytics.FieldTotalComments, dailyanalytics.FieldNewUsers, dailyanalytics.FieldNewPosts, dailyanalytics.FieldPublishedPosts:
			values[i] = new(sql.NullInt64)
		case dailyanalytics.FieldID:
			values[i] = new(sql.NullString)
		case dailyanalytics.FieldDate, dailyanalytics.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DailyAnalytics fields.
func (da *DailyAnalytics) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dailyanalytics.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				da.ID = value.String
			}
		case dailyanalytics.FieldDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date", values[i])
			} else if value.Valid {
				da.Date = value.Time
			}
		case dailyanalytics.FieldTotalViews:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_views", values[i])
			} else if value.Valid {
				da.TotalViews = int(value.Int64)
			}
		case dailyanalytics.FieldTotalComments:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_comments", values[i])
			} else if value.Valid {
				da.TotalComments = int(value.Int64)
			}
		case dailyanalytics.FieldNewUsers:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field new_users", values[i])
			} else if value.Valid {
				da.NewUsers = int(value.Int64)
			}
		case dailyanalytics.FieldNewPosts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field new_posts", values[i])
			} else if value.Valid {
				da.NewPosts = int(value.Int64)
			}
		case dailyanalytics.FieldPublishedPosts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field published_posts", values[i])
			} else if value.Valid {
				da.PublishedPosts = int(value.Int64)
			}
		case dailyanalytics.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				da.CreatedAt = value.Time
			}
		default:
			da.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DailyAnalytics.
// This includes values selected through modifiers, order, etc.
func (da *DailyAnalytics) Value(name string) (ent.Value, error) {
	return da.selectValues.Get(name)
}

// Update returns a builder for updating this DailyAnalytics.
// Note that you need to call DailyAnalytics.Unwrap() before calling this method if this DailyAnalytics
// was returned from a transaction, and the transaction was committed or rolled back.
func (da *DailyAnalytics) Update() *DailyAnalyticsUpdateOne {
	return NewDailyAnalyticsClient(da.config).UpdateOne(da)
}

// Unwrap unwraps the DailyAnalytics entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (da *DailyAnalytics) Unwrap() *DailyAnalytics {
	_tx, ok := da.config.driver.(*txDriver)
	if !ok {
		panic("ent: DailyAnalytics is not a transactional entity")
	}
	da.config.driver = _tx.drv
	return da
}

// String implements the fmt.Stringer.
func (da *DailyAnalytics) String() string {
	var builder strings.Builder
	builder.WriteString("DailyAnalytics(")
	builder.WriteString(fmt.Sprintf("id=%v, ", da.ID))
	builder.WriteString("date=")
	builder.WriteString(da.Date.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("total_views=")
	builder.WriteString(fmt.Sprintf("%v", da.TotalViews))
	builder.WriteString(", ")
	builder.WriteString("total_comments=")
	builder.WriteString(fmt.Sprintf("%v", da.TotalComments))
	builder.WriteString(", ")
	builder.WriteString("new_users=")
	builder.WriteString(fmt.Sprintf("%v", da.NewUsers))
	builder.WriteString(", ")
	builder.WriteString("new_posts=")
	builder.WriteString(fmt.Sprintf("%v", da.NewPosts))
	builder.WriteString(", ")
	builder.WriteString("published_posts=")
	builder.WriteString(fmt.Sprintf("%v", da.PublishedPosts))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(da.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DailyAnalyticsSlice is a parsable slice of DailyAnalytics.
type DailyAnalyticsSlice []*DailyAnalytics
