// Code generated by ent, DO NOT EDIT.

package ent

import (
	"biotak-go-backend/ent/dailyanalytics"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DailyAnalyticsCreate is the builder for creating a DailyAnalytics entity.
type DailyAnalyticsCreate struct {
	config
	mutation *DailyAnalyticsMutation
	hooks    []Hook
}

// SetDate sets the "date" field.
func (dac *DailyAnalyticsCreate) SetDate(t time.Time) *DailyAnalyticsCreate {
	dac.mutation.SetDate(t)
	return dac
}

// SetTotalViews sets the "total_views" field.
func (dac *DailyAnalyticsCreate) SetTotalViews(i int) *DailyAnalyticsCreate {
	dac.mutation.SetTotalViews(i)
	return dac
}

// SetNillableTotalViews sets the "total_views" field if the given value is not nil.
func (dac *DailyAnalyticsCreate) SetNillableTotalViews(i *int) *DailyAnalyticsCreate {
	if i != nil {
		dac.SetTotalViews(*i)
	}
	return dac
}

// SetTotalComments sets the "total_comments" field.
func (dac *DailyAnalyticsCreate) SetTotalComments(i int) *DailyAnalyticsCreate {
	dac.mutation.SetTotalComments(i)
	return dac
}

// SetNillableTotalComments sets the "total_comments" field if the given value is not nil.
func (dac *DailyAnalyticsCreate) SetNillableTotalComments(i *int) *DailyAnalyticsCreate {
	if i != nil {
		dac.SetTotalComments(*i)
	}
	return dac
}

// SetNewUsers sets the "new_users" field.
func (dac *DailyAnalyticsCreate) SetNewUsers(i int) *DailyAnalyticsCreate {
	dac.mutation.SetNewUsers(i)
	return dac
}

// SetNillableNewUsers sets the "new_users" field if the given value is not nil.
func (dac *DailyAnalyticsCreate) SetNillableNewUsers(i *int) *DailyAnalyticsCreate {
	if i != nil {
		dac.SetNewUsers(*i)
	}
	return dac
}

// SetNewPosts sets the "new_posts" field.
func (dac *DailyAnalyticsCreate) SetNewPosts(i int) *DailyAnalyticsCreate {
	dac.mutation.SetNewPosts(i)
	return dac
}

// SetNillableNewPosts sets the "new_posts" field if the given value is not nil.
func (dac *DailyAnalyticsCreate) SetNillableNewPosts(i *int) *DailyAnalyticsCreate {
	if i != nil {
		dac.SetNewPosts(*i)
	}
	return dac
}

// SetPublishedPosts sets the "published_posts" field.
func (dac *DailyAnalyticsCreate) SetPublishedPosts(i int) *DailyAnalyticsCreate {
	dac.mutation.SetPublishedPosts(i)
	return dac
}

// SetNillablePublishedPosts sets the "published_posts" field if the given value is not nil.
func (dac *DailyAnalyticsCreate) SetNillablePublishedPosts(i *int) *DailyAnalyticsCreate {
	if i != nil {
		dac.SetPublishedPosts(*i)
	}
	return dac
}

// SetCreatedAt sets the "created_at" field.
func (dac *DailyAnalyticsCreate) SetCreatedAt(t time.Time) *DailyAnalyticsCreate {
	dac.mutation.SetCreatedAt(t)
	return dac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (dac *DailyAnalyticsCreate) SetNillableCreatedAt(t *time.Time) *DailyAnalyticsCreate {
	if t != nil {
		dac.SetCreatedAt(*t)
	}
	return dac
}

// SetID sets the "id" field.
func (dac *DailyAnalyticsCreate) SetID(s string) *DailyAnalyticsCreate {
	dac.mutation.SetID(s)
	return dac
}

// Mutation returns the DailyAnalyticsMutation object of the builder.
func (dac *DailyAnalyticsCreate) Mutation() *DailyAnalyticsMutation {
	return dac.mutation
}

// Save creates the DailyAnalytics in the database.
func (dac *DailyAnalyticsCreate) Save(ctx context.Context) (*DailyAnalytics, error) {
	dac.defaults()
	return withHooks(ctx, dac.sqlSave, dac.mutation, dac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dac *DailyAnalyticsCreate) SaveX(ctx context.Context) *DailyAnalytics {
	v, err := dac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dac *DailyAnalyticsCreate) Exec(ctx context.Context) error {
	_, err := dac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dac *DailyAnalyticsCreate) ExecX(ctx context.Context) {
	if err := dac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dac *DailyAnalyticsCreate) defaults() {
	if _, ok := dac.mutation.TotalViews(); !ok {
		v := dailyanalytics.DefaultTotalViews
		dac.mutation.SetTotalViews(v)
	}
	if _, ok := dac.mutation.TotalComments(); !ok {
		v := dailyanalytics.DefaultTotalComments
		dac.mutation.SetTotalComments(v)
	}
	if _, ok := dac.mutation.NewUsers(); !ok {
		v := dailyanalytics.DefaultNewUsers
		dac.mutation.SetNewUsers(v)
	}
	if _, ok := dac.mutation.NewPosts(); !ok {
		v := dailyanalytics.DefaultNewPosts
		dac.mutation.SetNewPosts(v)
	}
	if _, ok := dac.mutation.PublishedPosts(); !ok {
		v := dailyanalytics.DefaultPublishedPosts
		dac.mutation.SetPublishedPosts(v)
	}
	if _, ok := dac.mutation.CreatedAt(); !ok {
		v := dailyanalytics.DefaultCreatedAt()
		dac.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dac *DailyAnalyticsCreate) check() error {
	if _, ok := dac.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New(`ent: missing required field "DailyAnalytics.date"`)}
	}
	if _, ok := dac.mutation.TotalViews(); !ok {
		return &ValidationError{Name: "total_views", err: errors.New(`ent: missing required field "DailyAnalytics.total_views"`)}
	}
	if v, ok := dac.mutation.TotalViews(); ok {
		if err := dailyanalytics.TotalViewsValidator(v); err != nil {
			return &ValidationError{Name: "total_views", err: fmt.Errorf(`ent: validator failed for field "DailyAnalytics.total_views": %w`, err)}
		}
	}
	if _, ok := dac.mutation.TotalComments(); !ok {
		return &ValidationError{Name: "total_comments", err: errors.New(`ent: missing required field "DailyAnalytics.total_comments"`)}
	}
	if v, ok := dac.mutation.TotalComments(); ok {
		if err := dailyanalytics.TotalCommentsValidator(v); err != nil {
			return &ValidationError{Name: "total_comments", err: fmt.Errorf(`ent: validator failed for field "DailyAnalytics.total_comments": %w`, err)}
		}
	}
	if _, ok := dac.mutation.NewUsers(); !ok {
		return &ValidationError{Name: "new_users", err: errors.New(`ent: missing required field "DailyAnalytics.new_users"`)}
	}
	if v, ok := dac.mutation.NewUsers(); ok {
		if err := dailyanalytics.NewUsersValidator(v); err != nil {
			return &ValidationError{Name: "new_users", err: fmt.Errorf(`ent: validator failed for field "DailyAnalytics.new_users": %w`, err)}
		}
	}
	if _, ok := dac.mutation.NewPosts(); !ok {
		return &ValidationError{Name: "new_posts", err: errors.New(`ent: missing required field "DailyAnalytics.new_posts"`)}
	}
	if v, ok := dac.mutation.NewPosts(); ok {
		if err := dailyanalytics.NewPostsValidator(v); err != nil {
			return &ValidationError{Name: "new_posts", err: fmt.Errorf(`ent: validator failed for field "DailyAnalytics.new_posts": %w`, err)}
		}
	}
	if _, ok := dac.mutation.PublishedPosts(); !ok {
		return &ValidationError{Name: "published_posts", err: errors.New(`ent: missing required field "DailyAnalytics.published_posts"`)}
	}
	if v, ok := dac.mutation.PublishedPosts(); ok {
		if err := dailyanalytics.PublishedPostsValidator(v); err != nil {
			return &ValidationError{Name: "published_posts", err: fmt.Errorf(`ent: validator failed for field "DailyAnalytics.published_posts": %w`, err)}
		}
	}
	if _, ok := dac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DailyAnalytics.created_at"`)}
	}
	return nil
}

func (dac *DailyAnalyticsCreate) sqlSave(ctx context.Context) (*DailyAnalytics, error) {
	if err := dac.check(); err != nil {
		return nil, err
	}
	_node, _spec := dac.createSpec()
	if err := sqlgraph.CreateNode(ctx, dac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected DailyAnalytics.ID type: %T", _spec.ID.Value)
		}
	}
	dac.mutation.id = &_node.ID
	dac.mutation.done = true
	return _node, nil
}

func (dac *DailyAnalyticsCreate) createSpec() (*DailyAnalytics, *sqlgraph.CreateSpec) {
	var (
		_node = &DailyAnalytics{config: dac.config}
		_spec = sqlgraph.NewCreateSpec(dailyanalytics.Table, sqlgraph.NewFieldSpec(dailyanalytics.FieldID, field.TypeString))
	)
	if id, ok := dac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := dac.mutation.Date(); ok {
		_spec.SetField(dailyanalytics.FieldDate, field.TypeTime, value)
		_node.Date = value
	}
	if value, ok := dac.mutation.TotalViews(); ok {
		_spec.SetField(dailyanalytics.FieldTotalViews, field.TypeInt, value)
		_node.TotalViews = value
	}
	if value, ok := dac.mutation.TotalComments(); ok {
		_spec.SetField(dailyanalytics.FieldTotalComments, field.TypeInt, value)
		_node.TotalComments = value
	}
	if value, ok := dac.mutation.NewUsers(); ok {
		_spec.SetField(dailyanalytics.FieldNewUsers, field.TypeInt, value)
		_node.NewUsers = value
	}
	if value, ok := dac.mutation.NewPosts(); ok {
		_spec.SetField(dailyanalytics.FieldNewPosts, field.TypeInt, value)
		_node.NewPosts = value
	}
	if value, ok := dac.mutation.PublishedPosts(); ok {
		_spec.SetField(dailyanalytics.FieldPublishedPosts, field.TypeInt, value)
		_node.PublishedPosts = value
	}
	if value, ok := dac.mutation.CreatedAt(); ok {
		_spec.SetField(dailyanalytics.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// DailyAnalyticsCreateBulk is the builder for creating many DailyAnalytics entities in bulk.
type DailyAnalyticsCreateBulk struct {
	config
	err      error
	builders []*DailyAnalyticsCreate
}

// Save creates the DailyAnalytics entities in the database.
func (dacb *DailyAnalyticsCreateBulk) Save(ctx context.Context) ([]*DailyAnalytics, error) {
	if dacb.err != nil {
		return nil, dacb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(dacb.builders))
	nodes := make([]*DailyAnalytics, len(dacb.builders))
	mutators := make([]Mutator, len(dacb.builders))
	for i := range dacb.builders {
		func(i int, root context.Context) {
			builder := dacb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DailyAnalyticsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dacb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dacb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dacb *DailyAnalyticsCreateBulk) SaveX(ctx context.Context) []*DailyAnalytics {
	v, err := dacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dacb *DailyAnalyticsCreateBulk) Exec(ctx context.Context) error {
	_, err := dacb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dacb *DailyAnalyticsCreateBulk) ExecX(ctx context.Context) {
	if err := dacb.Exec(ctx); err != nil {
		panic(err)
	}
}
