// Code generated by ent, DO NOT EDIT.

package ent

import (
	"biotak-go-backend/ent/dailyanalytics"
	"biotak-go-backend/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DailyAnalyticsQuery is the builder for querying DailyAnalytics entities.
type DailyAnalyticsQuery struct {
	config
	ctx        *QueryContext
	order      []dailyanalytics.OrderOption
	inters     []Interceptor
	predicates []predicate.DailyAnalytics
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DailyAnalyticsQuery builder.
func (daq *DailyAnalyticsQuery) Where(ps ...predicate.DailyAnalytics) *DailyAnalyticsQuery {
	daq.predicates = append(daq.predicates, ps...)
	return daq
}

// Limit the number of records to be returned by this query.
func (daq *DailyAnalyticsQuery) Limit(limit int) *DailyAnalyticsQuery {
	daq.ctx.Limit = &limit
	return daq
}

// Offset to start from.
func (daq *DailyAnalyticsQuery) Offset(offset int) *DailyAnalyticsQuery {
	daq.ctx.Offset = &offset
	return daq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (daq *DailyAnalyticsQuery) Unique(unique bool) *DailyAnalyticsQuery {
	daq.ctx.Unique = &unique
	return daq
}

// Order specifies how the records should be ordered.
func (daq *DailyAnalyticsQuery) Order(o ...dailyanalytics.OrderOption) *DailyAnalyticsQuery {
	daq.order = append(daq.order, o...)
	return daq
}

// First returns the first DailyAnalytics entity from the query.
// Returns a *NotFoundError when no DailyAnalytics was found.
func (daq *DailyAnalyticsQuery) First(ctx context.Context) (*DailyAnalytics, error) {
	nodes, err := daq.Limit(1).All(setContextOp(ctx, daq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{dailyanalytics.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (daq *DailyAnalyticsQuery) FirstX(ctx context.Context) *DailyAnalytics {
	node, err := daq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DailyAnalytics ID from the query.
// Returns a *NotFoundError when no DailyAnalytics ID was found.
func (daq *DailyAnalyticsQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = daq.Limit(1).IDs(setContextOp(ctx, daq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{dailyanalytics.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (daq *DailyAnalyticsQuery) FirstIDX(ctx context.Context) string {
	id, err := daq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DailyAnalytics entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DailyAnalytics entity is found.
// Returns a *NotFoundError when no DailyAnalytics entities are found.
func (daq *DailyAnalyticsQuery) Only(ctx context.Context) (*DailyAnalytics, error) {
	nodes, err := daq.Limit(2).All(setContextOp(ctx, daq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{dailyanalytics.Label}
	default:
		return nil, &NotSingularError{dailyanalytics.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (daq *DailyAnalyticsQuery) OnlyX(ctx context.Context) *DailyAnalytics {
	node, err := daq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DailyAnalytics ID in the query.
// Returns a *NotSingularError when more than one DailyAnalytics ID is found.
// Returns a *NotFoundError when no entities are found.
func (daq *DailyAnalyticsQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = daq.Limit(2).IDs(setContextOp(ctx, daq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{dailyanalytics.Label}
	default:
		err = &NotSingularError{dailyanalytics.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (daq *DailyAnalyticsQuery) OnlyIDX(ctx context.Context) string {
	id, err := daq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DailyAnalyticsSlice.
func (daq *DailyAnalyticsQuery) All(ctx context.Context) ([]*DailyAnalytics, error) {
	ctx = setContextOp(ctx, daq.ctx, "All")
	if err := daq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DailyAnalytics, *DailyAnalyticsQuery]()
	return withInterceptors[[]*DailyAnalytics](ctx, daq, qr, daq.inters)
}

// AllX is like All, but panics if an error occurs.
func (daq *DailyAnalyticsQuery) AllX(ctx context.Context) []*DailyAnalytics {
	nodes, err := daq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DailyAnalytics IDs.
func (daq *DailyAnalyticsQuery) IDs(ctx context.Context) (ids []string, err error) {
	if daq.ctx.Unique == nil && daq.path != nil {
		daq.Unique(true)
	}
	ctx = setContextOp(ctx, daq.ctx, "IDs")
	if err = daq.Select(dailyanalytics.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (daq *DailyAnalyticsQuery) IDsX(ctx context.Context) []string {
	ids, err := daq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (daq *DailyAnalyticsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, daq.ctx, "Count")
	if err := daq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, daq, querierCount[*DailyAnalyticsQuery](), daq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (daq *DailyAnalyticsQuery) CountX(ctx context.Context) int {
	count, err := daq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (daq *DailyAnalyticsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, daq.ctx, "Exist")
	switch _, err := daq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (daq *DailyAnalyticsQuery) ExistX(ctx context.Context) bool {
	exist, err := daq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DailyAnalyticsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (daq *DailyAnalyticsQuery) Clone() *DailyAnalyticsQuery {
	if daq == nil {
		return nil
	}
	return &DailyAnalyticsQuery{
		config:     daq.config,
		ctx:        daq.ctx.Clone(),
		order:      append([]dailyanalytics.OrderOption{}, daq.order...),
		inters:     append([]Interceptor{}, daq.inters...),
		predicates: append([]predicate.DailyAnalytics{}, daq.predicates...),
		// clone intermediate query.
		sql:  daq.sql.Clone(),
		path: daq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Date time.Time `json:"date,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DailyAnalytics.Query().
//		GroupBy(dailyanalytics.FieldDate).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (daq *DailyAnalyticsQuery) GroupBy(field string, fields ...string) *DailyAnalyticsGroupBy {
	daq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DailyAnalyticsGroupBy{build: daq}
	grbuild.flds = &daq.ctx.Fields
	grbuild.label = dailyanalytics.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Date time.Time `json:"date,omitempty"`
//	}
//
//	client.DailyAnalytics.Query().
//		Select(dailyanalytics.FieldDate).
//		Scan(ctx, &v)
func (daq *DailyAnalyticsQuery) Select(fields ...string) *DailyAnalyticsSelect {
	daq.ctx.Fields = append(daq.ctx.Fields, fields...)
	sbuild := &DailyAnalyticsSelect{DailyAnalyticsQuery: daq}
	sbuild.label = dailyanalytics.Label
	sbuild.flds, sbuild.scan = &daq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DailyAnalyticsSelect configured with the given aggregations.
func (daq *DailyAnalyticsQuery) Aggregate(fns ...AggregateFunc) *DailyAnalyticsSelect {
	return daq.Select().Aggregate(fns...)
}

func (daq *DailyAnalyticsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range daq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, daq); err != nil {
				return err
			}
		}
	}
	for _, f := range daq.ctx.Fields {
		if !dailyanalytics.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if daq.path != nil {
		prev, err := daq.path(ctx)
		if err != nil {
			return err
		}
		daq.sql = prev
	}
	return nil
}

func (daq *DailyAnalyticsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DailyAnalytics, error) {
	var (
		nodes = []*DailyAnalytics{}
		_spec = daq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DailyAnalytics).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DailyAnalytics{config: daq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, daq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (daq *DailyAnalyticsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := daq.querySpec()
	_spec.Node.Columns = daq.ctx.Fields
	if len(daq.ctx.Fields) > 0 {
		_spec.Unique = daq.ctx.Unique != nil && *daq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, daq.driver, _spec)
}

func (daq *DailyAnalyticsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(dailyanalytics.Table, dailyanalytics.Columns, sqlgraph.NewFieldSpec(dailyanalytics.FieldID, field.TypeString))
	_spec.From = daq.sql
	if unique := daq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if daq.path != nil {
		_spec.Unique = true
	}
	if fields := daq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dailyanalytics.FieldID)
		for i := range fields {
			if fields[i] != dailyanalytics.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := daq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := daq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := daq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := daq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (daq *DailyAnalyticsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(daq.driver.Dialect())
	t1 := builder.Table(dailyanalytics.Table)
	columns := daq.ctx.Fields
	if len(columns) == 0 {
		columns = dailyanalytics.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if daq.sql != nil {
		selector = daq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if daq.ctx.Unique != nil && *daq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range daq.predicates {
		p(selector)
	}
	for _, p := range daq.order {
		p(selector)
	}
	if offset := daq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := daq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DailyAnalyticsGroupBy is the group-by builder for DailyAnalytics entities.
type DailyAnalyticsGroupBy struct {
	selector
	build *DailyAnalyticsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dagb *DailyAnalyticsGroupBy) Aggregate(fns ...AggregateFunc) *DailyAnalyticsGroupBy {
	dagb.fns = append(dagb.fns, fns...)
	return dagb
}

// Scan applies the selector query and scans the result into the given value.
func (dagb *DailyAnalyticsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dagb.build.ctx, "GroupBy")
	if err := dagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DailyAnalyticsQuery, *DailyAnalyticsGroupBy](ctx, dagb.build, dagb, dagb.build.inters, v)
}

func (dagb *DailyAnalyticsGroupBy) sqlScan(ctx context.Context, root *DailyAnalyticsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(dagb.fns))
	for _, fn := range dagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*dagb.flds)+len(dagb.fns))
		for _, f := range *dagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*dagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DailyAnalyticsSelect is the builder for selecting fields of DailyAnalytics entities.
type DailyAnalyticsSelect struct {
	*DailyAnalyticsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (das *DailyAnalyticsSelect) Aggregate(fns ...AggregateFunc) *DailyAnalyticsSelect {
	das.fns = append(das.fns, fns...)
	return das
}

// Scan applies the selector query and scans the result into the given value.
func (das *DailyAnalyticsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, das.ctx, "Select")
	if err := das.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DailyAnalyticsQuery, *DailyAnalyticsSelect](ctx, das.DailyAnalyticsQuery, das, das.inters, v)
}

func (das *DailyAnalyticsSelect) sqlScan(ctx context.Context, root *DailyAnalyticsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(das.fns))
	for _, fn := range das.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*das.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := das.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
