// Code generated by ent, DO NOT EDIT.

package ent

import (
	"biotak-go-backend/ent/exchangerate"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ExchangeRate is the model entity for the ExchangeRate schema.
type ExchangeRate struct {
	config `json:"-"`
	// ID of the ent.
	// Exchange rate ID (cuid format)
	ID string `json:"id,omitempty"`
	// Exchange rate name/identifier
	Name string `json:"name,omitempty"`
	// Currency code (e.g., USD, EUR, BTC)
	Currency string `json:"currency,omitempty"`
	// Type of rate structure
	RateType exchangerate.RateType `json:"rate_type,omitempty"`
	// Buy rate (for BUY_SELL type)
	BuyRate *string `json:"buy_rate,omitempty"`
	// Sell rate (for BUY_SELL type)
	SellRate *string `json:"sell_rate,omitempty"`
	// Single rate (for SINGLE_BULK type)
	SingleRate *string `json:"single_rate,omitempty"`
	// Bulk rate (for SINGLE_BULK type)
	BulkRate *string `json:"bulk_rate,omitempty"`
	// Rate description
	Description *string `json:"description,omitempty"`
	// Currency/crypto icon URL
	ImageURL *string `json:"image_url,omitempty"`
	// Timestamp when rate was first created
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Timestamp when rate was last updated
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ExchangeRate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case exchangerate.FieldID, exchangerate.FieldName, exchangerate.FieldCurrency, exchangerate.FieldRateType, exchangerate.FieldBuyRate, exchangerate.FieldSellRate, exchangerate.FieldSingleRate, exchangerate.FieldBulkRate, exchangerate.FieldDescription, exchangerate.FieldImageURL:
			values[i] = new(sql.NullString)
		case exchangerate.FieldCreatedAt, exchangerate.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ExchangeRate fields.
func (er *ExchangeRate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case exchangerate.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				er.ID = value.String
			}
		case exchangerate.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				er.Name = value.String
			}
		case exchangerate.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				er.Currency = value.String
			}
		case exchangerate.FieldRateType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rate_type", values[i])
			} else if value.Valid {
				er.RateType = exchangerate.RateType(value.String)
			}
		case exchangerate.FieldBuyRate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field buy_rate", values[i])
			} else if value.Valid {
				er.BuyRate = new(string)
				*er.BuyRate = value.String
			}
		case exchangerate.FieldSellRate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sell_rate", values[i])
			} else if value.Valid {
				er.SellRate = new(string)
				*er.SellRate = value.String
			}
		case exchangerate.FieldSingleRate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field single_rate", values[i])
			} else if value.Valid {
				er.SingleRate = new(string)
				*er.SingleRate = value.String
			}
		case exchangerate.FieldBulkRate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bulk_rate", values[i])
			} else if value.Valid {
				er.BulkRate = new(string)
				*er.BulkRate = value.String
			}
		case exchangerate.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				er.Description = new(string)
				*er.Description = value.String
			}
		case exchangerate.FieldImageURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_url", values[i])
			} else if value.Valid {
				er.ImageURL = new(string)
				*er.ImageURL = value.String
			}
		case exchangerate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				er.CreatedAt = value.Time
			}
		case exchangerate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				er.UpdatedAt = value.Time
			}
		default:
			er.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ExchangeRate.
// This includes values selected through modifiers, order, etc.
func (er *ExchangeRate) Value(name string) (ent.Value, error) {
	return er.selectValues.Get(name)
}

// Update returns a builder for updating this ExchangeRate.
// Note that you need to call ExchangeRate.Unwrap() before calling this method if this ExchangeRate
// was returned from a transaction, and the transaction was committed or rolled back.
func (er *ExchangeRate) Update() *ExchangeRateUpdateOne {
	return NewExchangeRateClient(er.config).UpdateOne(er)
}

// Unwrap unwraps the ExchangeRate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (er *ExchangeRate) Unwrap() *ExchangeRate {
	_tx, ok := er.config.driver.(*txDriver)
	if !ok {
		panic("ent: ExchangeRate is not a transactional entity")
	}
	er.config.driver = _tx.drv
	return er
}

// String implements the fmt.Stringer.
func (er *ExchangeRate) String() string {
	var builder strings.Builder
	builder.WriteString("ExchangeRate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", er.ID))
	builder.WriteString("name=")
	builder.WriteString(er.Name)
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(er.Currency)
	builder.WriteString(", ")
	builder.WriteString("rate_type=")
	builder.WriteString(fmt.Sprintf("%v", er.RateType))
	builder.WriteString(", ")
	if v := er.BuyRate; v != nil {
		builder.WriteString("buy_rate=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := er.SellRate; v != nil {
		builder.WriteString("sell_rate=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := er.SingleRate; v != nil {
		builder.WriteString("single_rate=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := er.BulkRate; v != nil {
		builder.WriteString("bulk_rate=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := er.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := er.ImageURL; v != nil {
		builder.WriteString("image_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(er.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(er.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ExchangeRates is a parsable slice of ExchangeRate.
type ExchangeRates []*ExchangeRate
