// Code generated by ent, DO NOT EDIT.

package ent

import (
	"biotak-go-backend/ent/exchangerate"
	"biotak-go-backend/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExchangeRateQuery is the builder for querying ExchangeRate entities.
type ExchangeRateQuery struct {
	config
	ctx        *QueryContext
	order      []exchangerate.OrderOption
	inters     []Interceptor
	predicates []predicate.ExchangeRate
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ExchangeRateQuery builder.
func (erq *ExchangeRateQuery) Where(ps ...predicate.ExchangeRate) *ExchangeRateQuery {
	erq.predicates = append(erq.predicates, ps...)
	return erq
}

// Limit the number of records to be returned by this query.
func (erq *ExchangeRateQuery) Limit(limit int) *ExchangeRateQuery {
	erq.ctx.Limit = &limit
	return erq
}

// Offset to start from.
func (erq *ExchangeRateQuery) Offset(offset int) *ExchangeRateQuery {
	erq.ctx.Offset = &offset
	return erq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (erq *ExchangeRateQuery) Unique(unique bool) *ExchangeRateQuery {
	erq.ctx.Unique = &unique
	return erq
}

// Order specifies how the records should be ordered.
func (erq *ExchangeRateQuery) Order(o ...exchangerate.OrderOption) *ExchangeRateQuery {
	erq.order = append(erq.order, o...)
	return erq
}

// First returns the first ExchangeRate entity from the query.
// Returns a *NotFoundError when no ExchangeRate was found.
func (erq *ExchangeRateQuery) First(ctx context.Context) (*ExchangeRate, error) {
	nodes, err := erq.Limit(1).All(setContextOp(ctx, erq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{exchangerate.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (erq *ExchangeRateQuery) FirstX(ctx context.Context) *ExchangeRate {
	node, err := erq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ExchangeRate ID from the query.
// Returns a *NotFoundError when no ExchangeRate ID was found.
func (erq *ExchangeRateQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = erq.Limit(1).IDs(setContextOp(ctx, erq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{exchangerate.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (erq *ExchangeRateQuery) FirstIDX(ctx context.Context) string {
	id, err := erq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ExchangeRate entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ExchangeRate entity is found.
// Returns a *NotFoundError when no ExchangeRate entities are found.
func (erq *ExchangeRateQuery) Only(ctx context.Context) (*ExchangeRate, error) {
	nodes, err := erq.Limit(2).All(setContextOp(ctx, erq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{exchangerate.Label}
	default:
		return nil, &NotSingularError{exchangerate.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (erq *ExchangeRateQuery) OnlyX(ctx context.Context) *ExchangeRate {
	node, err := erq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ExchangeRate ID in the query.
// Returns a *NotSingularError when more than one ExchangeRate ID is found.
// Returns a *NotFoundError when no entities are found.
func (erq *ExchangeRateQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = erq.Limit(2).IDs(setContextOp(ctx, erq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{exchangerate.Label}
	default:
		err = &NotSingularError{exchangerate.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (erq *ExchangeRateQuery) OnlyIDX(ctx context.Context) string {
	id, err := erq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ExchangeRates.
func (erq *ExchangeRateQuery) All(ctx context.Context) ([]*ExchangeRate, error) {
	ctx = setContextOp(ctx, erq.ctx, "All")
	if err := erq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ExchangeRate, *ExchangeRateQuery]()
	return withInterceptors[[]*ExchangeRate](ctx, erq, qr, erq.inters)
}

// AllX is like All, but panics if an error occurs.
func (erq *ExchangeRateQuery) AllX(ctx context.Context) []*ExchangeRate {
	nodes, err := erq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ExchangeRate IDs.
func (erq *ExchangeRateQuery) IDs(ctx context.Context) (ids []string, err error) {
	if erq.ctx.Unique == nil && erq.path != nil {
		erq.Unique(true)
	}
	ctx = setContextOp(ctx, erq.ctx, "IDs")
	if err = erq.Select(exchangerate.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (erq *ExchangeRateQuery) IDsX(ctx context.Context) []string {
	ids, err := erq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (erq *ExchangeRateQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, erq.ctx, "Count")
	if err := erq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, erq, querierCount[*ExchangeRateQuery](), erq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (erq *ExchangeRateQuery) CountX(ctx context.Context) int {
	count, err := erq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (erq *ExchangeRateQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, erq.ctx, "Exist")
	switch _, err := erq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (erq *ExchangeRateQuery) ExistX(ctx context.Context) bool {
	exist, err := erq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ExchangeRateQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (erq *ExchangeRateQuery) Clone() *ExchangeRateQuery {
	if erq == nil {
		return nil
	}
	return &ExchangeRateQuery{
		config:     erq.config,
		ctx:        erq.ctx.Clone(),
		order:      append([]exchangerate.OrderOption{}, erq.order...),
		inters:     append([]Interceptor{}, erq.inters...),
		predicates: append([]predicate.ExchangeRate{}, erq.predicates...),
		// clone intermediate query.
		sql:  erq.sql.Clone(),
		path: erq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ExchangeRate.Query().
//		GroupBy(exchangerate.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (erq *ExchangeRateQuery) GroupBy(field string, fields ...string) *ExchangeRateGroupBy {
	erq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ExchangeRateGroupBy{build: erq}
	grbuild.flds = &erq.ctx.Fields
	grbuild.label = exchangerate.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.ExchangeRate.Query().
//		Select(exchangerate.FieldName).
//		Scan(ctx, &v)
func (erq *ExchangeRateQuery) Select(fields ...string) *ExchangeRateSelect {
	erq.ctx.Fields = append(erq.ctx.Fields, fields...)
	sbuild := &ExchangeRateSelect{ExchangeRateQuery: erq}
	sbuild.label = exchangerate.Label
	sbuild.flds, sbuild.scan = &erq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ExchangeRateSelect configured with the given aggregations.
func (erq *ExchangeRateQuery) Aggregate(fns ...AggregateFunc) *ExchangeRateSelect {
	return erq.Select().Aggregate(fns...)
}

func (erq *ExchangeRateQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range erq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, erq); err != nil {
				return err
			}
		}
	}
	for _, f := range erq.ctx.Fields {
		if !exchangerate.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if erq.path != nil {
		prev, err := erq.path(ctx)
		if err != nil {
			return err
		}
		erq.sql = prev
	}
	return nil
}

func (erq *ExchangeRateQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ExchangeRate, error) {
	var (
		nodes = []*ExchangeRate{}
		_spec = erq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ExchangeRate).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ExchangeRate{config: erq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, erq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (erq *ExchangeRateQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := erq.querySpec()
	_spec.Node.Columns = erq.ctx.Fields
	if len(erq.ctx.Fields) > 0 {
		_spec.Unique = erq.ctx.Unique != nil && *erq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, erq.driver, _spec)
}

func (erq *ExchangeRateQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(exchangerate.Table, exchangerate.Columns, sqlgraph.NewFieldSpec(exchangerate.FieldID, field.TypeString))
	_spec.From = erq.sql
	if unique := erq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if erq.path != nil {
		_spec.Unique = true
	}
	if fields := erq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, exchangerate.FieldID)
		for i := range fields {
			if fields[i] != exchangerate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := erq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := erq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := erq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := erq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (erq *ExchangeRateQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(erq.driver.Dialect())
	t1 := builder.Table(exchangerate.Table)
	columns := erq.ctx.Fields
	if len(columns) == 0 {
		columns = exchangerate.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if erq.sql != nil {
		selector = erq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if erq.ctx.Unique != nil && *erq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range erq.predicates {
		p(selector)
	}
	for _, p := range erq.order {
		p(selector)
	}
	if offset := erq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := erq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ExchangeRateGroupBy is the group-by builder for ExchangeRate entities.
type ExchangeRateGroupBy struct {
	selector
	build *ExchangeRateQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ergb *ExchangeRateGroupBy) Aggregate(fns ...AggregateFunc) *ExchangeRateGroupBy {
	ergb.fns = append(ergb.fns, fns...)
	return ergb
}

// Scan applies the selector query and scans the result into the given value.
func (ergb *ExchangeRateGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ergb.build.ctx, "GroupBy")
	if err := ergb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ExchangeRateQuery, *ExchangeRateGroupBy](ctx, ergb.build, ergb, ergb.build.inters, v)
}

func (ergb *ExchangeRateGroupBy) sqlScan(ctx context.Context, root *ExchangeRateQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ergb.fns))
	for _, fn := range ergb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ergb.flds)+len(ergb.fns))
		for _, f := range *ergb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ergb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ergb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ExchangeRateSelect is the builder for selecting fields of ExchangeRate entities.
type ExchangeRateSelect struct {
	*ExchangeRateQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ers *ExchangeRateSelect) Aggregate(fns ...AggregateFunc) *ExchangeRateSelect {
	ers.fns = append(ers.fns, fns...)
	return ers
}

// Scan applies the selector query and scans the result into the given value.
func (ers *ExchangeRateSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ers.ctx, "Select")
	if err := ers.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ExchangeRateQuery, *ExchangeRateSelect](ctx, ers.ExchangeRateQuery, ers, ers.inters, v)
}

func (ers *ExchangeRateSelect) sqlScan(ctx context.Context, root *ExchangeRateQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ers.fns))
	for _, fn := range ers.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ers.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ers.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
