// Code generated by ent, DO NOT EDIT.

package ent

import (
	"biotak-go-backend/ent/newsletter"
	"biotak-go-backend/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Newsletter is the model entity for the Newsletter schema.
type Newsletter struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID *string `json:"user_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NewsletterQuery when eager-loading is set.
	Edges        NewsletterEdges `json:"edges"`
	selectValues sql.SelectValues
}

// NewsletterEdges holds the relations/edges for other nodes in the graph.
type NewsletterEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NewsletterEdges) UserOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.User == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Newsletter) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case newsletter.FieldIsActive:
			values[i] = new(sql.NullBool)
		case newsletter.FieldID, newsletter.FieldEmail, newsletter.FieldUserID:
			values[i] = new(sql.NullString)
		case newsletter.FieldCreatedAt, newsletter.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Newsletter fields.
func (n *Newsletter) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case newsletter.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				n.ID = value.String
			}
		case newsletter.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				n.Email = value.String
			}
		case newsletter.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				n.IsActive = value.Bool
			}
		case newsletter.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				n.UserID = new(string)
				*n.UserID = value.String
			}
		case newsletter.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				n.CreatedAt = value.Time
			}
		case newsletter.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				n.UpdatedAt = value.Time
			}
		default:
			n.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Newsletter.
// This includes values selected through modifiers, order, etc.
func (n *Newsletter) Value(name string) (ent.Value, error) {
	return n.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Newsletter entity.
func (n *Newsletter) QueryUser() *UserQuery {
	return NewNewsletterClient(n.config).QueryUser(n)
}

// Update returns a builder for updating this Newsletter.
// Note that you need to call Newsletter.Unwrap() before calling this method if this Newsletter
// was returned from a transaction, and the transaction was committed or rolled back.
func (n *Newsletter) Update() *NewsletterUpdateOne {
	return NewNewsletterClient(n.config).UpdateOne(n)
}

// Unwrap unwraps the Newsletter entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (n *Newsletter) Unwrap() *Newsletter {
	_tx, ok := n.config.driver.(*txDriver)
	if !ok {
		panic("ent: Newsletter is not a transactional entity")
	}
	n.config.driver = _tx.drv
	return n
}

// String implements the fmt.Stringer.
func (n *Newsletter) String() string {
	var builder strings.Builder
	builder.WriteString("Newsletter(")
	builder.WriteString(fmt.Sprintf("id=%v, ", n.ID))
	builder.WriteString("email=")
	builder.WriteString(n.Email)
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", n.IsActive))
	builder.WriteString(", ")
	if v := n.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(n.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(n.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Newsletters is a parsable slice of Newsletter.
type Newsletters []*Newsletter
