// Code generated by ent, DO NOT EDIT.

package ent

import (
	"biotak-go-backend/ent/newsletter"
	"biotak-go-backend/ent/predicate"
	"biotak-go-backend/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NewsletterUpdate is the builder for updating Newsletter entities.
type NewsletterUpdate struct {
	config
	hooks    []Hook
	mutation *NewsletterMutation
}

// Where appends a list predicates to the NewsletterUpdate builder.
func (nu *NewsletterUpdate) Where(ps ...predicate.Newsletter) *NewsletterUpdate {
	nu.mutation.Where(ps...)
	return nu
}

// SetEmail sets the "email" field.
func (nu *NewsletterUpdate) SetEmail(s string) *NewsletterUpdate {
	nu.mutation.SetEmail(s)
	return nu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (nu *NewsletterUpdate) SetNillableEmail(s *string) *NewsletterUpdate {
	if s != nil {
		nu.SetEmail(*s)
	}
	return nu
}

// SetIsActive sets the "is_active" field.
func (nu *NewsletterUpdate) SetIsActive(b bool) *NewsletterUpdate {
	nu.mutation.SetIsActive(b)
	return nu
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (nu *NewsletterUpdate) SetNillableIsActive(b *bool) *NewsletterUpdate {
	if b != nil {
		nu.SetIsActive(*b)
	}
	return nu
}

// SetUserID sets the "user_id" field.
func (nu *NewsletterUpdate) SetUserID(s string) *NewsletterUpdate {
	nu.mutation.SetUserID(s)
	return nu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (nu *NewsletterUpdate) SetNillableUserID(s *string) *NewsletterUpdate {
	if s != nil {
		nu.SetUserID(*s)
	}
	return nu
}

// ClearUserID clears the value of the "user_id" field.
func (nu *NewsletterUpdate) ClearUserID() *NewsletterUpdate {
	nu.mutation.ClearUserID()
	return nu
}

// SetUpdatedAt sets the "updated_at" field.
func (nu *NewsletterUpdate) SetUpdatedAt(t time.Time) *NewsletterUpdate {
	nu.mutation.SetUpdatedAt(t)
	return nu
}

// SetUser sets the "user" edge to the User entity.
func (nu *NewsletterUpdate) SetUser(u *User) *NewsletterUpdate {
	return nu.SetUserID(u.ID)
}

// Mutation returns the NewsletterMutation object of the builder.
func (nu *NewsletterUpdate) Mutation() *NewsletterMutation {
	return nu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (nu *NewsletterUpdate) ClearUser() *NewsletterUpdate {
	nu.mutation.ClearUser()
	return nu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (nu *NewsletterUpdate) Save(ctx context.Context) (int, error) {
	nu.defaults()
	return withHooks(ctx, nu.sqlSave, nu.mutation, nu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nu *NewsletterUpdate) SaveX(ctx context.Context) int {
	affected, err := nu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (nu *NewsletterUpdate) Exec(ctx context.Context) error {
	_, err := nu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nu *NewsletterUpdate) ExecX(ctx context.Context) {
	if err := nu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nu *NewsletterUpdate) defaults() {
	if _, ok := nu.mutation.UpdatedAt(); !ok {
		v := newsletter.UpdateDefaultUpdatedAt()
		nu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nu *NewsletterUpdate) check() error {
	if v, ok := nu.mutation.Email(); ok {
		if err := newsletter.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Newsletter.email": %w`, err)}
		}
	}
	return nil
}

func (nu *NewsletterUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := nu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(newsletter.Table, newsletter.Columns, sqlgraph.NewFieldSpec(newsletter.FieldID, field.TypeString))
	if ps := nu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nu.mutation.Email(); ok {
		_spec.SetField(newsletter.FieldEmail, field.TypeString, value)
	}
	if value, ok := nu.mutation.IsActive(); ok {
		_spec.SetField(newsletter.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := nu.mutation.UpdatedAt(); ok {
		_spec.SetField(newsletter.FieldUpdatedAt, field.TypeTime, value)
	}
	if nu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   newsletter.UserTable,
			Columns: []string{newsletter.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   newsletter.UserTable,
			Columns: []string{newsletter.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, nu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{newsletter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	nu.mutation.done = true
	return n, nil
}

// NewsletterUpdateOne is the builder for updating a single Newsletter entity.
type NewsletterUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NewsletterMutation
}

// SetEmail sets the "email" field.
func (nuo *NewsletterUpdateOne) SetEmail(s string) *NewsletterUpdateOne {
	nuo.mutation.SetEmail(s)
	return nuo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (nuo *NewsletterUpdateOne) SetNillableEmail(s *string) *NewsletterUpdateOne {
	if s != nil {
		nuo.SetEmail(*s)
	}
	return nuo
}

// SetIsActive sets the "is_active" field.
func (nuo *NewsletterUpdateOne) SetIsActive(b bool) *NewsletterUpdateOne {
	nuo.mutation.SetIsActive(b)
	return nuo
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (nuo *NewsletterUpdateOne) SetNillableIsActive(b *bool) *NewsletterUpdateOne {
	if b != nil {
		nuo.SetIsActive(*b)
	}
	return nuo
}

// SetUserID sets the "user_id" field.
func (nuo *NewsletterUpdateOne) SetUserID(s string) *NewsletterUpdateOne {
	nuo.mutation.SetUserID(s)
	return nuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (nuo *NewsletterUpdateOne) SetNillableUserID(s *string) *NewsletterUpdateOne {
	if s != nil {
		nuo.SetUserID(*s)
	}
	return nuo
}

// ClearUserID clears the value of the "user_id" field.
func (nuo *NewsletterUpdateOne) ClearUserID() *NewsletterUpdateOne {
	nuo.mutation.ClearUserID()
	return nuo
}

// SetUpdatedAt sets the "updated_at" field.
func (nuo *NewsletterUpdateOne) SetUpdatedAt(t time.Time) *NewsletterUpdateOne {
	nuo.mutation.SetUpdatedAt(t)
	return nuo
}

// SetUser sets the "user" edge to the User entity.
func (nuo *NewsletterUpdateOne) SetUser(u *User) *NewsletterUpdateOne {
	return nuo.SetUserID(u.ID)
}

// Mutation returns the NewsletterMutation object of the builder.
func (nuo *NewsletterUpdateOne) Mutation() *NewsletterMutation {
	return nuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (nuo *NewsletterUpdateOne) ClearUser() *NewsletterUpdateOne {
	nuo.mutation.ClearUser()
	return nuo
}

// Where appends a list predicates to the NewsletterUpdate builder.
func (nuo *NewsletterUpdateOne) Where(ps ...predicate.Newsletter) *NewsletterUpdateOne {
	nuo.mutation.Where(ps...)
	return nuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (nuo *NewsletterUpdateOne) Select(field string, fields ...string) *NewsletterUpdateOne {
	nuo.fields = append([]string{field}, fields...)
	return nuo
}

// Save executes the query and returns the updated Newsletter entity.
func (nuo *NewsletterUpdateOne) Save(ctx context.Context) (*Newsletter, error) {
	nuo.defaults()
	return withHooks(ctx, nuo.sqlSave, nuo.mutation, nuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nuo *NewsletterUpdateOne) SaveX(ctx context.Context) *Newsletter {
	node, err := nuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (nuo *NewsletterUpdateOne) Exec(ctx context.Context) error {
	_, err := nuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nuo *NewsletterUpdateOne) ExecX(ctx context.Context) {
	if err := nuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nuo *NewsletterUpdateOne) defaults() {
	if _, ok := nuo.mutation.UpdatedAt(); !ok {
		v := newsletter.UpdateDefaultUpdatedAt()
		nuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nuo *NewsletterUpdateOne) check() error {
	if v, ok := nuo.mutation.Email(); ok {
		if err := newsletter.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Newsletter.email": %w`, err)}
		}
	}
	return nil
}

func (nuo *NewsletterUpdateOne) sqlSave(ctx context.Context) (_node *Newsletter, err error) {
	if err := nuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(newsletter.Table, newsletter.Columns, sqlgraph.NewFieldSpec(newsletter.FieldID, field.TypeString))
	id, ok := nuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Newsletter.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := nuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, newsletter.FieldID)
		for _, f := range fields {
			if !newsletter.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != newsletter.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := nuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nuo.mutation.Email(); ok {
		_spec.SetField(newsletter.FieldEmail, field.TypeString, value)
	}
	if value, ok := nuo.mutation.IsActive(); ok {
		_spec.SetField(newsletter.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := nuo.mutation.UpdatedAt(); ok {
		_spec.SetField(newsletter.FieldUpdatedAt, field.TypeTime, value)
	}
	if nuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   newsletter.UserTable,
			Columns: []string{newsletter.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   newsletter.UserTable,
			Columns: []string{newsletter.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Newsletter{config: nuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, nuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{newsletter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	nuo.mutation.done = true
	return _node, nil
}
