// Code generated by ent, DO NOT EDIT.

package ent

import (
	"biotak-go-backend/ent/post"
	"biotak-go-backend/ent/user"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Post is the model entity for the Post schema.
type Post struct {
	config `json:"-"`
	// ID of the ent.
	// Post ID (cuid format)
	ID string `json:"id,omitempty"`
	// Post title
	Title string `json:"title,omitempty"`
	// URL-friendly slug
	Slug string `json:"slug,omitempty"`
	// Post content (HTML/Markdown)
	Content string `json:"content,omitempty"`
	// Post excerpt/summary
	Excerpt *string `json:"excerpt,omitempty"`
	// Featured image URL
	FeaturedImage *string `json:"featured_image,omitempty"`
	// Gallery images for GALLERY post type
	GalleryImages []string `json:"gallery_images,omitempty"`
	// Post publication status
	Status post.Status `json:"status,omitempty"`
	// Type of post content
	PostType post.PostType `json:"post_type,omitempty"`
	// Whether post is featured
	IsFeatured bool `json:"is_featured,omitempty"`
	// Video URL for VIDEO post type
	VideoURL *string `json:"video_url,omitempty"`
	// Audio URL for AUDIO post type
	AudioURL *string `json:"audio_url,omitempty"`
	// Number of views
	ViewCount int `json:"view_count,omitempty"`
	// Estimated reading time in minutes
	ReadingTime int `json:"reading_time,omitempty"`
	// Author user ID
	AuthorID string `json:"author_id,omitempty"`
	// Timestamp when post was created
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Timestamp when post was last updated
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Soft delete timestamp
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PostQuery when eager-loading is set.
	Edges        PostEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PostEdges holds the relations/edges for other nodes in the graph.
type PostEdges struct {
	// Post author
	Author *User `json:"author,omitempty"`
	// Comments on this post
	Comments []*Comment `json:"comments,omitempty"`
	// Categories this post belongs to
	Categories []*Category `json:"categories,omitempty"`
	// Tags associated with this post
	Tags []*Tag `json:"tags,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// AuthorOrErr returns the Author value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PostEdges) AuthorOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.Author == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.Author, nil
	}
	return nil, &NotLoadedError{edge: "author"}
}

// CommentsOrErr returns the Comments value or an error if the edge
// was not loaded in eager-loading.
func (e PostEdges) CommentsOrErr() ([]*Comment, error) {
	if e.loadedTypes[1] {
		return e.Comments, nil
	}
	return nil, &NotLoadedError{edge: "comments"}
}

// CategoriesOrErr returns the Categories value or an error if the edge
// was not loaded in eager-loading.
func (e PostEdges) CategoriesOrErr() ([]*Category, error) {
	if e.loadedTypes[2] {
		return e.Categories, nil
	}
	return nil, &NotLoadedError{edge: "categories"}
}

// TagsOrErr returns the Tags value or an error if the edge
// was not loaded in eager-loading.
func (e PostEdges) TagsOrErr() ([]*Tag, error) {
	if e.loadedTypes[3] {
		return e.Tags, nil
	}
	return nil, &NotLoadedError{edge: "tags"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Post) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case post.FieldGalleryImages:
			values[i] = new([]byte)
		case post.FieldIsFeatured:
			values[i] = new(sql.NullBool)
		case post.FieldViewCount, post.FieldReadingTime:
			values[i] = new(sql.NullInt64)
		case post.FieldID, post.FieldTitle, post.FieldSlug, post.FieldContent, post.FieldExcerpt, post.FieldFeaturedImage, post.FieldStatus, post.FieldPostType, post.FieldVideoURL, post.FieldAudioURL, post.FieldAuthorID:
			values[i] = new(sql.NullString)
		case post.FieldCreatedAt, post.FieldUpdatedAt, post.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Post fields.
func (po *Post) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case post.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				po.ID = value.String
			}
		case post.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				po.Title = value.String
			}
		case post.FieldSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slug", values[i])
			} else if value.Valid {
				po.Slug = value.String
			}
		case post.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				po.Content = value.String
			}
		case post.FieldExcerpt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field excerpt", values[i])
			} else if value.Valid {
				po.Excerpt = new(string)
				*po.Excerpt = value.String
			}
		case post.FieldFeaturedImage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field featured_image", values[i])
			} else if value.Valid {
				po.FeaturedImage = new(string)
				*po.FeaturedImage = value.String
			}
		case post.FieldGalleryImages:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field gallery_images", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &po.GalleryImages); err != nil {
					return fmt.Errorf("unmarshal field gallery_images: %w", err)
				}
			}
		case post.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				po.Status = post.Status(value.String)
			}
		case post.FieldPostType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field post_type", values[i])
			} else if value.Valid {
				po.PostType = post.PostType(value.String)
			}
		case post.FieldIsFeatured:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_featured", values[i])
			} else if value.Valid {
				po.IsFeatured = value.Bool
			}
		case post.FieldVideoURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field video_url", values[i])
			} else if value.Valid {
				po.VideoURL = new(string)
				*po.VideoURL = value.String
			}
		case post.FieldAudioURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field audio_url", values[i])
			} else if value.Valid {
				po.AudioURL = new(string)
				*po.AudioURL = value.String
			}
		case post.FieldViewCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field view_count", values[i])
			} else if value.Valid {
				po.ViewCount = int(value.Int64)
			}
		case post.FieldReadingTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reading_time", values[i])
			} else if value.Valid {
				po.ReadingTime = int(value.Int64)
			}
		case post.FieldAuthorID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field author_id", values[i])
			} else if value.Valid {
				po.AuthorID = value.String
			}
		case post.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				po.CreatedAt = value.Time
			}
		case post.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				po.UpdatedAt = value.Time
			}
		case post.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				po.DeletedAt = new(time.Time)
				*po.DeletedAt = value.Time
			}
		default:
			po.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Post.
// This includes values selected through modifiers, order, etc.
func (po *Post) Value(name string) (ent.Value, error) {
	return po.selectValues.Get(name)
}

// QueryAuthor queries the "author" edge of the Post entity.
func (po *Post) QueryAuthor() *UserQuery {
	return NewPostClient(po.config).QueryAuthor(po)
}

// QueryComments queries the "comments" edge of the Post entity.
func (po *Post) QueryComments() *CommentQuery {
	return NewPostClient(po.config).QueryComments(po)
}

// QueryCategories queries the "categories" edge of the Post entity.
func (po *Post) QueryCategories() *CategoryQuery {
	return NewPostClient(po.config).QueryCategories(po)
}

// QueryTags queries the "tags" edge of the Post entity.
func (po *Post) QueryTags() *TagQuery {
	return NewPostClient(po.config).QueryTags(po)
}

// Update returns a builder for updating this Post.
// Note that you need to call Post.Unwrap() before calling this method if this Post
// was returned from a transaction, and the transaction was committed or rolled back.
func (po *Post) Update() *PostUpdateOne {
	return NewPostClient(po.config).UpdateOne(po)
}

// Unwrap unwraps the Post entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (po *Post) Unwrap() *Post {
	_tx, ok := po.config.driver.(*txDriver)
	if !ok {
		panic("ent: Post is not a transactional entity")
	}
	po.config.driver = _tx.drv
	return po
}

// String implements the fmt.Stringer.
func (po *Post) String() string {
	var builder strings.Builder
	builder.WriteString("Post(")
	builder.WriteString(fmt.Sprintf("id=%v, ", po.ID))
	builder.WriteString("title=")
	builder.WriteString(po.Title)
	builder.WriteString(", ")
	builder.WriteString("slug=")
	builder.WriteString(po.Slug)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(po.Content)
	builder.WriteString(", ")
	if v := po.Excerpt; v != nil {
		builder.WriteString("excerpt=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := po.FeaturedImage; v != nil {
		builder.WriteString("featured_image=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("gallery_images=")
	builder.WriteString(fmt.Sprintf("%v", po.GalleryImages))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", po.Status))
	builder.WriteString(", ")
	builder.WriteString("post_type=")
	builder.WriteString(fmt.Sprintf("%v", po.PostType))
	builder.WriteString(", ")
	builder.WriteString("is_featured=")
	builder.WriteString(fmt.Sprintf("%v", po.IsFeatured))
	builder.WriteString(", ")
	if v := po.VideoURL; v != nil {
		builder.WriteString("video_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := po.AudioURL; v != nil {
		builder.WriteString("audio_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("view_count=")
	builder.WriteString(fmt.Sprintf("%v", po.ViewCount))
	builder.WriteString(", ")
	builder.WriteString("reading_time=")
	builder.WriteString(fmt.Sprintf("%v", po.ReadingTime))
	builder.WriteString(", ")
	builder.WriteString("author_id=")
	builder.WriteString(po.AuthorID)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(po.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(po.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := po.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Posts is a parsable slice of Post.
type Posts []*Post
