// Code generated by ent, DO NOT EDIT.

package ent

import (
	"biotak-go-backend/ent/predicate"
	"biotak-go-backend/ent/profile"
	"biotak-go-backend/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProfileUpdate is the builder for updating Profile entities.
type ProfileUpdate struct {
	config
	hooks    []Hook
	mutation *ProfileMutation
}

// Where appends a list predicates to the ProfileUpdate builder.
func (pu *ProfileUpdate) Where(ps ...predicate.Profile) *ProfileUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetBio sets the "bio" field.
func (pu *ProfileUpdate) SetBio(s string) *ProfileUpdate {
	pu.mutation.SetBio(s)
	return pu
}

// SetNillableBio sets the "bio" field if the given value is not nil.
func (pu *ProfileUpdate) SetNillableBio(s *string) *ProfileUpdate {
	if s != nil {
		pu.SetBio(*s)
	}
	return pu
}

// ClearBio clears the value of the "bio" field.
func (pu *ProfileUpdate) ClearBio() *ProfileUpdate {
	pu.mutation.ClearBio()
	return pu
}

// SetAvatar sets the "avatar" field.
func (pu *ProfileUpdate) SetAvatar(s string) *ProfileUpdate {
	pu.mutation.SetAvatar(s)
	return pu
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (pu *ProfileUpdate) SetNillableAvatar(s *string) *ProfileUpdate {
	if s != nil {
		pu.SetAvatar(*s)
	}
	return pu
}

// ClearAvatar clears the value of the "avatar" field.
func (pu *ProfileUpdate) ClearAvatar() *ProfileUpdate {
	pu.mutation.ClearAvatar()
	return pu
}

// SetBgImage sets the "bg_image" field.
func (pu *ProfileUpdate) SetBgImage(s string) *ProfileUpdate {
	pu.mutation.SetBgImage(s)
	return pu
}

// SetNillableBgImage sets the "bg_image" field if the given value is not nil.
func (pu *ProfileUpdate) SetNillableBgImage(s *string) *ProfileUpdate {
	if s != nil {
		pu.SetBgImage(*s)
	}
	return pu
}

// ClearBgImage clears the value of the "bg_image" field.
func (pu *ProfileUpdate) ClearBgImage() *ProfileUpdate {
	pu.mutation.ClearBgImage()
	return pu
}

// SetJobName sets the "job_name" field.
func (pu *ProfileUpdate) SetJobName(s string) *ProfileUpdate {
	pu.mutation.SetJobName(s)
	return pu
}

// SetNillableJobName sets the "job_name" field if the given value is not nil.
func (pu *ProfileUpdate) SetNillableJobName(s *string) *ProfileUpdate {
	if s != nil {
		pu.SetJobName(*s)
	}
	return pu
}

// ClearJobName clears the value of the "job_name" field.
func (pu *ProfileUpdate) ClearJobName() *ProfileUpdate {
	pu.mutation.ClearJobName()
	return pu
}

// SetCompany sets the "company" field.
func (pu *ProfileUpdate) SetCompany(s string) *ProfileUpdate {
	pu.mutation.SetCompany(s)
	return pu
}

// SetNillableCompany sets the "company" field if the given value is not nil.
func (pu *ProfileUpdate) SetNillableCompany(s *string) *ProfileUpdate {
	if s != nil {
		pu.SetCompany(*s)
	}
	return pu
}

// ClearCompany clears the value of the "company" field.
func (pu *ProfileUpdate) ClearCompany() *ProfileUpdate {
	pu.mutation.ClearCompany()
	return pu
}

// SetUserID sets the "user_id" field.
func (pu *ProfileUpdate) SetUserID(s string) *ProfileUpdate {
	pu.mutation.SetUserID(s)
	return pu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (pu *ProfileUpdate) SetNillableUserID(s *string) *ProfileUpdate {
	if s != nil {
		pu.SetUserID(*s)
	}
	return pu
}

// SetUser sets the "user" edge to the User entity.
func (pu *ProfileUpdate) SetUser(u *User) *ProfileUpdate {
	return pu.SetUserID(u.ID)
}

// Mutation returns the ProfileMutation object of the builder.
func (pu *ProfileUpdate) Mutation() *ProfileMutation {
	return pu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (pu *ProfileUpdate) ClearUser() *ProfileUpdate {
	pu.mutation.ClearUser()
	return pu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *ProfileUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *ProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *ProfileUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *ProfileUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *ProfileUpdate) check() error {
	if v, ok := pu.mutation.UserID(); ok {
		if err := profile.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Profile.user_id": %w`, err)}
		}
	}
	if _, ok := pu.mutation.UserID(); pu.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Profile.user"`)
	}
	return nil
}

func (pu *ProfileUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(profile.Table, profile.Columns, sqlgraph.NewFieldSpec(profile.FieldID, field.TypeString))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Bio(); ok {
		_spec.SetField(profile.FieldBio, field.TypeString, value)
	}
	if pu.mutation.BioCleared() {
		_spec.ClearField(profile.FieldBio, field.TypeString)
	}
	if value, ok := pu.mutation.Avatar(); ok {
		_spec.SetField(profile.FieldAvatar, field.TypeString, value)
	}
	if pu.mutation.AvatarCleared() {
		_spec.ClearField(profile.FieldAvatar, field.TypeString)
	}
	if value, ok := pu.mutation.BgImage(); ok {
		_spec.SetField(profile.FieldBgImage, field.TypeString, value)
	}
	if pu.mutation.BgImageCleared() {
		_spec.ClearField(profile.FieldBgImage, field.TypeString)
	}
	if value, ok := pu.mutation.JobName(); ok {
		_spec.SetField(profile.FieldJobName, field.TypeString, value)
	}
	if pu.mutation.JobNameCleared() {
		_spec.ClearField(profile.FieldJobName, field.TypeString)
	}
	if value, ok := pu.mutation.Company(); ok {
		_spec.SetField(profile.FieldCompany, field.TypeString, value)
	}
	if pu.mutation.CompanyCleared() {
		_spec.ClearField(profile.FieldCompany, field.TypeString)
	}
	if pu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   profile.UserTable,
			Columns: []string{profile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   profile.UserTable,
			Columns: []string{profile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{profile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// ProfileUpdateOne is the builder for updating a single Profile entity.
type ProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProfileMutation
}

// SetBio sets the "bio" field.
func (puo *ProfileUpdateOne) SetBio(s string) *ProfileUpdateOne {
	puo.mutation.SetBio(s)
	return puo
}

// SetNillableBio sets the "bio" field if the given value is not nil.
func (puo *ProfileUpdateOne) SetNillableBio(s *string) *ProfileUpdateOne {
	if s != nil {
		puo.SetBio(*s)
	}
	return puo
}

// ClearBio clears the value of the "bio" field.
func (puo *ProfileUpdateOne) ClearBio() *ProfileUpdateOne {
	puo.mutation.ClearBio()
	return puo
}

// SetAvatar sets the "avatar" field.
func (puo *ProfileUpdateOne) SetAvatar(s string) *ProfileUpdateOne {
	puo.mutation.SetAvatar(s)
	return puo
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (puo *ProfileUpdateOne) SetNillableAvatar(s *string) *ProfileUpdateOne {
	if s != nil {
		puo.SetAvatar(*s)
	}
	return puo
}

// ClearAvatar clears the value of the "avatar" field.
func (puo *ProfileUpdateOne) ClearAvatar() *ProfileUpdateOne {
	puo.mutation.ClearAvatar()
	return puo
}

// SetBgImage sets the "bg_image" field.
func (puo *ProfileUpdateOne) SetBgImage(s string) *ProfileUpdateOne {
	puo.mutation.SetBgImage(s)
	return puo
}

// SetNillableBgImage sets the "bg_image" field if the given value is not nil.
func (puo *ProfileUpdateOne) SetNillableBgImage(s *string) *ProfileUpdateOne {
	if s != nil {
		puo.SetBgImage(*s)
	}
	return puo
}

// ClearBgImage clears the value of the "bg_image" field.
func (puo *ProfileUpdateOne) ClearBgImage() *ProfileUpdateOne {
	puo.mutation.ClearBgImage()
	return puo
}

// SetJobName sets the "job_name" field.
func (puo *ProfileUpdateOne) SetJobName(s string) *ProfileUpdateOne {
	puo.mutation.SetJobName(s)
	return puo
}

// SetNillableJobName sets the "job_name" field if the given value is not nil.
func (puo *ProfileUpdateOne) SetNillableJobName(s *string) *ProfileUpdateOne {
	if s != nil {
		puo.SetJobName(*s)
	}
	return puo
}

// ClearJobName clears the value of the "job_name" field.
func (puo *ProfileUpdateOne) ClearJobName() *ProfileUpdateOne {
	puo.mutation.ClearJobName()
	return puo
}

// SetCompany sets the "company" field.
func (puo *ProfileUpdateOne) SetCompany(s string) *ProfileUpdateOne {
	puo.mutation.SetCompany(s)
	return puo
}

// SetNillableCompany sets the "company" field if the given value is not nil.
func (puo *ProfileUpdateOne) SetNillableCompany(s *string) *ProfileUpdateOne {
	if s != nil {
		puo.SetCompany(*s)
	}
	return puo
}

// ClearCompany clears the value of the "company" field.
func (puo *ProfileUpdateOne) ClearCompany() *ProfileUpdateOne {
	puo.mutation.ClearCompany()
	return puo
}

// SetUserID sets the "user_id" field.
func (puo *ProfileUpdateOne) SetUserID(s string) *ProfileUpdateOne {
	puo.mutation.SetUserID(s)
	return puo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (puo *ProfileUpdateOne) SetNillableUserID(s *string) *ProfileUpdateOne {
	if s != nil {
		puo.SetUserID(*s)
	}
	return puo
}

// SetUser sets the "user" edge to the User entity.
func (puo *ProfileUpdateOne) SetUser(u *User) *ProfileUpdateOne {
	return puo.SetUserID(u.ID)
}

// Mutation returns the ProfileMutation object of the builder.
func (puo *ProfileUpdateOne) Mutation() *ProfileMutation {
	return puo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (puo *ProfileUpdateOne) ClearUser() *ProfileUpdateOne {
	puo.mutation.ClearUser()
	return puo
}

// Where appends a list predicates to the ProfileUpdate builder.
func (puo *ProfileUpdateOne) Where(ps ...predicate.Profile) *ProfileUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *ProfileUpdateOne) Select(field string, fields ...string) *ProfileUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Profile entity.
func (puo *ProfileUpdateOne) Save(ctx context.Context) (*Profile, error) {
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *ProfileUpdateOne) SaveX(ctx context.Context) *Profile {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *ProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *ProfileUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *ProfileUpdateOne) check() error {
	if v, ok := puo.mutation.UserID(); ok {
		if err := profile.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Profile.user_id": %w`, err)}
		}
	}
	if _, ok := puo.mutation.UserID(); puo.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Profile.user"`)
	}
	return nil
}

func (puo *ProfileUpdateOne) sqlSave(ctx context.Context) (_node *Profile, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(profile.Table, profile.Columns, sqlgraph.NewFieldSpec(profile.FieldID, field.TypeString))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Profile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, profile.FieldID)
		for _, f := range fields {
			if !profile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != profile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.Bio(); ok {
		_spec.SetField(profile.FieldBio, field.TypeString, value)
	}
	if puo.mutation.BioCleared() {
		_spec.ClearField(profile.FieldBio, field.TypeString)
	}
	if value, ok := puo.mutation.Avatar(); ok {
		_spec.SetField(profile.FieldAvatar, field.TypeString, value)
	}
	if puo.mutation.AvatarCleared() {
		_spec.ClearField(profile.FieldAvatar, field.TypeString)
	}
	if value, ok := puo.mutation.BgImage(); ok {
		_spec.SetField(profile.FieldBgImage, field.TypeString, value)
	}
	if puo.mutation.BgImageCleared() {
		_spec.ClearField(profile.FieldBgImage, field.TypeString)
	}
	if value, ok := puo.mutation.JobName(); ok {
		_spec.SetField(profile.FieldJobName, field.TypeString, value)
	}
	if puo.mutation.JobNameCleared() {
		_spec.ClearField(profile.FieldJobName, field.TypeString)
	}
	if value, ok := puo.mutation.Company(); ok {
		_spec.SetField(profile.FieldCompany, field.TypeString, value)
	}
	if puo.mutation.CompanyCleared() {
		_spec.ClearField(profile.FieldCompany, field.TypeString)
	}
	if puo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   profile.UserTable,
			Columns: []string{profile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   profile.UserTable,
			Columns: []string{profile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Profile{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{profile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
