// Code generated by ent, DO NOT EDIT.

package ent

import (
	"biotak-go-backend/ent/category"
	"biotak-go-backend/ent/comment"
	"biotak-go-backend/ent/exchangerate"
	"biotak-go-backend/ent/post"
	"biotak-go-backend/ent/profile"
	"biotak-go-backend/ent/schema"
	"biotak-go-backend/ent/tag"
	"biotak-go-backend/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescName is the schema descriptor for name field.
	categoryDescName := categoryFields[1].Descriptor()
	// category.NameValidator is a validator for the "name" field. It is called by the builders before save.
	category.NameValidator = categoryDescName.Validators[0].(func(string) error)
	// categoryDescSlug is the schema descriptor for slug field.
	categoryDescSlug := categoryFields[2].Descriptor()
	// category.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	category.SlugValidator = categoryDescSlug.Validators[0].(func(string) error)
	// categoryDescCreatedAt is the schema descriptor for created_at field.
	categoryDescCreatedAt := categoryFields[5].Descriptor()
	// category.DefaultCreatedAt holds the default value on creation for the created_at field.
	category.DefaultCreatedAt = categoryDescCreatedAt.Default.(func() time.Time)
	// categoryDescUpdatedAt is the schema descriptor for updated_at field.
	categoryDescUpdatedAt := categoryFields[6].Descriptor()
	// category.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	category.DefaultUpdatedAt = categoryDescUpdatedAt.Default.(func() time.Time)
	// category.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	category.UpdateDefaultUpdatedAt = categoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// categoryDescID is the schema descriptor for id field.
	categoryDescID := categoryFields[0].Descriptor()
	// category.IDValidator is a validator for the "id" field. It is called by the builders before save.
	category.IDValidator = func() func(string) error {
		validators := categoryDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescContent is the schema descriptor for content field.
	commentDescContent := commentFields[1].Descriptor()
	// comment.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	comment.ContentValidator = commentDescContent.Validators[0].(func(string) error)
	// commentDescApproved is the schema descriptor for approved field.
	commentDescApproved := commentFields[2].Descriptor()
	// comment.DefaultApproved holds the default value on creation for the approved field.
	comment.DefaultApproved = commentDescApproved.Default.(bool)
	// commentDescPostID is the schema descriptor for post_id field.
	commentDescPostID := commentFields[3].Descriptor()
	// comment.PostIDValidator is a validator for the "post_id" field. It is called by the builders before save.
	comment.PostIDValidator = commentDescPostID.Validators[0].(func(string) error)
	// commentDescAuthorID is the schema descriptor for author_id field.
	commentDescAuthorID := commentFields[4].Descriptor()
	// comment.AuthorIDValidator is a validator for the "author_id" field. It is called by the builders before save.
	comment.AuthorIDValidator = commentDescAuthorID.Validators[0].(func(string) error)
	// commentDescCreatedAt is the schema descriptor for created_at field.
	commentDescCreatedAt := commentFields[6].Descriptor()
	// comment.DefaultCreatedAt holds the default value on creation for the created_at field.
	comment.DefaultCreatedAt = commentDescCreatedAt.Default.(func() time.Time)
	// commentDescUpdatedAt is the schema descriptor for updated_at field.
	commentDescUpdatedAt := commentFields[7].Descriptor()
	// comment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	comment.DefaultUpdatedAt = commentDescUpdatedAt.Default.(func() time.Time)
	// comment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	comment.UpdateDefaultUpdatedAt = commentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// commentDescID is the schema descriptor for id field.
	commentDescID := commentFields[0].Descriptor()
	// comment.IDValidator is a validator for the "id" field. It is called by the builders before save.
	comment.IDValidator = func() func(string) error {
		validators := commentDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	exchangerateFields := schema.ExchangeRate{}.Fields()
	_ = exchangerateFields
	// exchangerateDescName is the schema descriptor for name field.
	exchangerateDescName := exchangerateFields[1].Descriptor()
	// exchangerate.NameValidator is a validator for the "name" field. It is called by the builders before save.
	exchangerate.NameValidator = exchangerateDescName.Validators[0].(func(string) error)
	// exchangerateDescCurrency is the schema descriptor for currency field.
	exchangerateDescCurrency := exchangerateFields[2].Descriptor()
	// exchangerate.CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	exchangerate.CurrencyValidator = exchangerateDescCurrency.Validators[0].(func(string) error)
	// exchangerateDescCreatedAt is the schema descriptor for created_at field.
	exchangerateDescCreatedAt := exchangerateFields[10].Descriptor()
	// exchangerate.DefaultCreatedAt holds the default value on creation for the created_at field.
	exchangerate.DefaultCreatedAt = exchangerateDescCreatedAt.Default.(func() time.Time)
	// exchangerateDescUpdatedAt is the schema descriptor for updated_at field.
	exchangerateDescUpdatedAt := exchangerateFields[11].Descriptor()
	// exchangerate.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	exchangerate.DefaultUpdatedAt = exchangerateDescUpdatedAt.Default.(func() time.Time)
	// exchangerate.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	exchangerate.UpdateDefaultUpdatedAt = exchangerateDescUpdatedAt.UpdateDefault.(func() time.Time)
	// exchangerateDescID is the schema descriptor for id field.
	exchangerateDescID := exchangerateFields[0].Descriptor()
	// exchangerate.IDValidator is a validator for the "id" field. It is called by the builders before save.
	exchangerate.IDValidator = func() func(string) error {
		validators := exchangerateDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	postFields := schema.Post{}.Fields()
	_ = postFields
	// postDescTitle is the schema descriptor for title field.
	postDescTitle := postFields[1].Descriptor()
	// post.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	post.TitleValidator = postDescTitle.Validators[0].(func(string) error)
	// postDescSlug is the schema descriptor for slug field.
	postDescSlug := postFields[2].Descriptor()
	// post.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	post.SlugValidator = postDescSlug.Validators[0].(func(string) error)
	// postDescContent is the schema descriptor for content field.
	postDescContent := postFields[3].Descriptor()
	// post.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	post.ContentValidator = postDescContent.Validators[0].(func(string) error)
	// postDescIsFeatured is the schema descriptor for is_featured field.
	postDescIsFeatured := postFields[9].Descriptor()
	// post.DefaultIsFeatured holds the default value on creation for the is_featured field.
	post.DefaultIsFeatured = postDescIsFeatured.Default.(bool)
	// postDescViewCount is the schema descriptor for view_count field.
	postDescViewCount := postFields[12].Descriptor()
	// post.DefaultViewCount holds the default value on creation for the view_count field.
	post.DefaultViewCount = postDescViewCount.Default.(int)
	// post.ViewCountValidator is a validator for the "view_count" field. It is called by the builders before save.
	post.ViewCountValidator = postDescViewCount.Validators[0].(func(int) error)
	// postDescReadingTime is the schema descriptor for reading_time field.
	postDescReadingTime := postFields[13].Descriptor()
	// post.DefaultReadingTime holds the default value on creation for the reading_time field.
	post.DefaultReadingTime = postDescReadingTime.Default.(int)
	// post.ReadingTimeValidator is a validator for the "reading_time" field. It is called by the builders before save.
	post.ReadingTimeValidator = postDescReadingTime.Validators[0].(func(int) error)
	// postDescAuthorID is the schema descriptor for author_id field.
	postDescAuthorID := postFields[14].Descriptor()
	// post.AuthorIDValidator is a validator for the "author_id" field. It is called by the builders before save.
	post.AuthorIDValidator = postDescAuthorID.Validators[0].(func(string) error)
	// postDescCreatedAt is the schema descriptor for created_at field.
	postDescCreatedAt := postFields[15].Descriptor()
	// post.DefaultCreatedAt holds the default value on creation for the created_at field.
	post.DefaultCreatedAt = postDescCreatedAt.Default.(func() time.Time)
	// postDescUpdatedAt is the schema descriptor for updated_at field.
	postDescUpdatedAt := postFields[16].Descriptor()
	// post.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	post.DefaultUpdatedAt = postDescUpdatedAt.Default.(func() time.Time)
	// post.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	post.UpdateDefaultUpdatedAt = postDescUpdatedAt.UpdateDefault.(func() time.Time)
	// postDescID is the schema descriptor for id field.
	postDescID := postFields[0].Descriptor()
	// post.IDValidator is a validator for the "id" field. It is called by the builders before save.
	post.IDValidator = func() func(string) error {
		validators := postDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	profileFields := schema.Profile{}.Fields()
	_ = profileFields
	// profileDescUserID is the schema descriptor for user_id field.
	profileDescUserID := profileFields[6].Descriptor()
	// profile.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	profile.UserIDValidator = profileDescUserID.Validators[0].(func(string) error)
	// profileDescID is the schema descriptor for id field.
	profileDescID := profileFields[0].Descriptor()
	// profile.IDValidator is a validator for the "id" field. It is called by the builders before save.
	profile.IDValidator = func() func(string) error {
		validators := profileDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	tagFields := schema.Tag{}.Fields()
	_ = tagFields
	// tagDescName is the schema descriptor for name field.
	tagDescName := tagFields[1].Descriptor()
	// tag.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tag.NameValidator = tagDescName.Validators[0].(func(string) error)
	// tagDescSlug is the schema descriptor for slug field.
	tagDescSlug := tagFields[2].Descriptor()
	// tag.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	tag.SlugValidator = tagDescSlug.Validators[0].(func(string) error)
	// tagDescCreatedAt is the schema descriptor for created_at field.
	tagDescCreatedAt := tagFields[4].Descriptor()
	// tag.DefaultCreatedAt holds the default value on creation for the created_at field.
	tag.DefaultCreatedAt = tagDescCreatedAt.Default.(func() time.Time)
	// tagDescUpdatedAt is the schema descriptor for updated_at field.
	tagDescUpdatedAt := tagFields[5].Descriptor()
	// tag.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tag.DefaultUpdatedAt = tagDescUpdatedAt.Default.(func() time.Time)
	// tag.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tag.UpdateDefaultUpdatedAt = tagDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tagDescID is the schema descriptor for id field.
	tagDescID := tagFields[0].Descriptor()
	// tag.IDValidator is a validator for the "id" field. It is called by the builders before save.
	tag.IDValidator = func() func(string) error {
		validators := tagDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[6].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(string)
	// userDescEmailVerified is the schema descriptor for email_verified field.
	userDescEmailVerified := userFields[7].Descriptor()
	// user.DefaultEmailVerified holds the default value on creation for the email_verified field.
	user.DefaultEmailVerified = userDescEmailVerified.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[9].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[10].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = func() func(string) error {
		validators := userDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
}
